//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_BANKS_UNITS_ACTIONS
    {
        public int ABU_ID { get; set; }
        public int ABUA_ACTION { get; set; }
    
        public virtual AC_BANKS_UNITS AC_BANKS_UNITS { get; set; }
    }
}
