//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_BANKS_UNITS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AC_BANKS_UNITS()
        {
            this.AC_BANKS_UNITS_ACTIONS = new HashSet<AC_BANKS_UNITS_ACTIONS>();
        }
    
        public int ABU_ID { get; set; }
        public decimal AB_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime ABU_EDIT_TIME { get; set; }
        public bool ABU_VISIBILITY { get; set; }
    
        public virtual AC_BANKS AC_BANKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_BANKS_UNITS_ACTIONS> AC_BANKS_UNITS_ACTIONS { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
