//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_INTEGRATION_TRANSFERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AC_INTEGRATION_TRANSFERS()
        {
            this.AC_INTEGRATION_TRANSFERS_PAYMENT = new HashSet<AC_INTEGRATION_TRANSFERS_PAYMENT>();
            this.AC_INTEGRATION_TRANSFERS_ACCURALS = new HashSet<AC_INTEGRATION_TRANSFERS_ACCURALS>();
        }
    
        public decimal ACIT_ID { get; set; }
        public System.DateTime ACIT_DATE_LOAD { get; set; }
        public decimal ACIT_SUM { get; set; }
        public bool ACIT_IS_GIVED { get; set; }
        public System.DateTime ACIT_GIVED_DATE { get; set; }
        public decimal ACIT_USER_MADE { get; set; }
        public decimal ACIT_USER_TRANSFERRED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_INTEGRATION_TRANSFERS_PAYMENT> AC_INTEGRATION_TRANSFERS_PAYMENT { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual SC_USERS SC_USERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_INTEGRATION_TRANSFERS_ACCURALS> AC_INTEGRATION_TRANSFERS_ACCURALS { get; set; }
    }
}
