//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_INTEGRATION_TRANSFERS_PAYMENT
    {
        public int ACITAC_ID { get; set; }
        public decimal ACIT_ID { get; set; }
        public int CALC_ID { get; set; }
    
        public virtual AC_INTEGRATION_TRANSFERS AC_INTEGRATION_TRANSFERS { get; set; }
        public virtual WR_PAYMENT WR_PAYMENT { get; set; }
    }
}
