//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_MONEY_HIST
    {
        public decimal MH_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime MH_DATETIME_START { get; set; }
        public Nullable<System.DateTime> MH_DATETIME_END { get; set; }
        public decimal MH_CASH_GIVE { get; set; }
        public Nullable<decimal> MH_CASH_LAST { get; set; }
        public Nullable<bool> MH_IS_CLOSED { get; set; }
    }
}
