//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_ACTION_NUMBER_SHIFTS
    {
        public int AANS_ID { get; set; }
        public int AA_ID { get; set; }
        public int NUMBER_SHIFTS { get; set; }
    
        public virtual ACT_ACTIONS ACT_ACTIONS { get; set; }
    }
}
