//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALFA_NEW_REGIONS
    {
        public int KLADR_ID { get; set; }
        public string ALFA_ID { get; set; }
        public string ALFA_TYPE { get; set; }
    }
}
