//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVE_WR_WAGES
    {
        public decimal CL_ID { get; set; }
        public string WT_NAME { get; set; }
        public decimal WRG_ID { get; set; }
        public decimal WRW_COST { get; set; }
        public decimal WRW_COST_INC { get; set; }
        public decimal WRW_HOURS_INC { get; set; }
        public decimal WGP_ID { get; set; }
        public decimal WRW_COST_LMK { get; set; }
    }
}
