//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCH_STATUSES
    {
        public System.DateTime AS_DATE { get; set; }
        public decimal ST_ID { get; set; }
        public decimal AS_COUNT { get; set; }
    }
}
