//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_TRANSFERS_PAYMENT_HISTORY
    {
        public int BTPH_ID { get; set; }
        public int ACBF_ID { get; set; }
        public int PH_ID { get; set; }
    
        public virtual BANK_TRANSFERS BANK_TRANSFERS { get; set; }
        public virtual WR_PAYMENT_HISTORY WR_PAYMENT_HISTORY { get; set; }
    }
}
