//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_TRANSFERS_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANK_TRANSFERS_STATUS()
        {
            this.BANK_TRANSFERS_HISTORY = new HashSet<BANK_TRANSFERS_HISTORY>();
        }
    
        public int TS_ID { get; set; }
        public string Name { get; set; }
        public string KeyChar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANK_TRANSFERS_HISTORY> BANK_TRANSFERS_HISTORY { get; set; }
    }
}
