//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_TRANSFERS_HISTORY
    {
        public int BTH_ID { get; set; }
        public decimal US_ID { get; set; }
        public int ACBF_ID { get; set; }
        public int TS_ID { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
    
        public virtual BANK_TRANSFERS BANK_TRANSFERS { get; set; }
        public virtual BANK_TRANSFERS_STATUS BANK_TRANSFERS_STATUS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
