//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_TRANSFERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANK_TRANSFERS()
        {
            this.BANK_TRANSFERS_HISTORY = new HashSet<BANK_TRANSFERS_HISTORY>();
            this.BANK_TRANSFERS_PAYMENT_HISTORY = new HashSet<BANK_TRANSFERS_PAYMENT_HISTORY>();
        }
    
        public int ACBF_ID { get; set; }
        public System.DateTime ACBF_DATE_LOAD { get; set; }
        public decimal ACBF_SUM { get; set; }
        public decimal ACBF_BID { get; set; }
    
        public virtual AC_BANKS AC_BANKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANK_TRANSFERS_HISTORY> BANK_TRANSFERS_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANK_TRANSFERS_PAYMENT_HISTORY> BANK_TRANSFERS_PAYMENT_HISTORY { get; set; }
    }
}
