//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_BLOCK
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public Nullable<System.DateTime> CC_BLOCK_TILL { get; set; }
        public string CC_BLOCKED_PHONE { get; set; }
        public int BLOCK_TYPE { get; set; }
    
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
