//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_IPTEL_USERS_STATUSES
    {
        public decimal US_ID { get; set; }
        public decimal CIU_STATUS { get; set; }
        public System.DateTime CIU_ACTIVE_AT { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
