//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_IPTEL_LOGS
    {
        public decimal CIL_ID { get; set; }
        public Nullable<decimal> CIL_ORDER_ID { get; set; }
        public Nullable<decimal> CIL_UN_ID { get; set; }
        public Nullable<decimal> CIL_WR_ID { get; set; }
        public decimal CIL_ACTION_TYPE { get; set; }
        public decimal CIL_USER { get; set; }
        public System.DateTime CIL_AT_TIME { get; set; }
        public string CIL_SID { get; set; }
    
        public virtual CC_IPTEL_LOG_TYPES CC_IPTEL_LOG_TYPES { get; set; }
        public virtual OR_ORDER OR_ORDER { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
