//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_IPTEL_TASK_CAMPAIGN
    {
        public int CITC_ID { get; set; }
        public Nullable<decimal> CIT_ID { get; set; }
        public Nullable<decimal> CGN_ID { get; set; }
    
        public virtual CGN_CAMPAIGN CGN_CAMPAIGN { get; set; }
        public virtual CC_IPTEL_TASKS CC_IPTEL_TASKS { get; set; }
    }
}
