//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_MANAGER_TASK_WORKERS
    {
        public int TASK_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public string COMMENT { get; set; }
        public bool IS_CALLED { get; set; }
        public int ID { get; set; }
    
        public virtual CC_MANAGER_TASK CC_MANAGER_TASK { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
