//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_MANAGER_TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CC_MANAGER_TASK()
        {
            this.CC_MANAGER_TASK_CANDIDATES = new HashSet<CC_MANAGER_TASK_CANDIDATES>();
            this.CC_MANAGER_TASK_WORKERS = new HashSet<CC_MANAGER_TASK_WORKERS>();
        }
    
        public int TASK_ID { get; set; }
        public decimal CIT_ID { get; set; }
        public string WORK_TYPE { get; set; }
        public int CALL_LIST_TYPE_ID { get; set; }
        public decimal US_ID { get; set; }
        public string COMMENT { get; set; }
        public decimal UN_ID { get; set; }
    
        public virtual CC_IPTEL_TASKS CC_IPTEL_TASKS { get; set; }
        public virtual CC_MANAGER_TASK_TYPE CC_MANAGER_TASK_TYPE { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_MANAGER_TASK_CANDIDATES> CC_MANAGER_TASK_CANDIDATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_MANAGER_TASK_WORKERS> CC_MANAGER_TASK_WORKERS { get; set; }
    }
}
