//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_REG_GIVE_MONEY
    {
        public decimal CCRG_ID { get; set; }
        public decimal US_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public System.DateTime CCRG_DATE { get; set; }
        public System.DateTime CCRG_THEN_DATE { get; set; }
        public decimal CCRG_THERE_UNIT { get; set; }
        public decimal CCRG_THERE_PLACE { get; set; }
        public decimal CCRG_TOTAL_SUM { get; set; }
        public bool CCRG_SUM_PREPAY { get; set; }
        public decimal CCRG_MANAGER { get; set; }
    }
}
