//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGN_CAMPAIGN_WORKERS
    {
        public decimal CGN_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public bool CGNW_COMPLETE { get; set; }
        public bool CGNW_RECALL { get; set; }
        public System.DateTime CGNW_COMPLETE_TIME { get; set; }
    
        public virtual OR_TRAIN_CENTER_WORKERS_CAMPAIGN OR_TRAIN_CENTER_WORKERS_CAMPAIGN { get; set; }
    }
}
