//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGN_BONUS_OPTIONS
    {
        public decimal CGNBO_NET_ID { get; set; }
        public decimal CGNBO_ORDERS_FOR_CALC { get; set; }
        public decimal CGNBO_SUM { get; set; }
    
        public virtual CL_NETS CL_NETS { get; set; }
    }
}
