//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGN_QUEUE_ACTUALISATION
    {
        public decimal CGNQA_ID { get; set; }
        public decimal CGN_ID { get; set; }
        public decimal CGNQA_STAGE { get; set; }
        public System.DateTime CGNQA_STARTED_TIME { get; set; }
        public System.DateTime CGNQA_DONE_TIME { get; set; }
        public bool CGNQA_DONE { get; set; }
        public bool CGNQA_STAFFED { get; set; }
        public decimal CGNQUAP_POOL_ID { get; set; }
    
        public virtual CGN_CAMPAIGN CGN_CAMPAIGN { get; set; }
    }
}
