//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGN_CAMPAIGN_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGN_CAMPAIGN_TYPES()
        {
            this.CGN_CAMPAIGN = new HashSet<CGN_CAMPAIGN>();
        }
    
        public decimal CGNT_ID { get; set; }
        public string CGNT_NAME { get; set; }
        public string CGNT_COMMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGN_CAMPAIGN> CGN_CAMPAIGN { get; set; }
    }
}
