//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGNT_FIN_UNIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGNT_FIN_UNIT()
        {
            this.CGNT_CONTRAGENT = new HashSet<CGNT_CONTRAGENT>();
            this.CGNT_FIN_UNIT_UNIT = new HashSet<CGNT_FIN_UNIT_UNIT>();
        }
    
        public int CUN_ID { get; set; }
        public Nullable<System.Guid> CUN_FIN_ID { get; set; }
        public string CUN_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGNT_CONTRAGENT> CGNT_CONTRAGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGNT_FIN_UNIT_UNIT> CGNT_FIN_UNIT_UNIT { get; set; }
    }
}
