//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGNT_BILL_ITEM
    {
        public int BLTM_ID { get; set; }
        public int BL_ID { get; set; }
        public int FWT_ID { get; set; }
        public Nullable<decimal> BLTM_COST_HUMAN_HOUR { get; set; }
        public Nullable<decimal> BLTM_VOLUME { get; set; }
        public Nullable<decimal> BLTM_SUM { get; set; }
        public Nullable<int> BLTM_TAX { get; set; }
        public Nullable<decimal> BLTM_TAX_SUM { get; set; }
    
        public virtual CGNT_BILL CGNT_BILL { get; set; }
        public virtual OPT_FIN_WORK_TYPES OPT_FIN_WORK_TYPES { get; set; }
    }
}
