//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGNT_CONTRAGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGNT_CONTRAGENT()
        {
            this.CGNT_BILL = new HashSet<CGNT_BILL>();
            this.CL_CLIENTS_CONTRAGENT = new HashSet<CL_CLIENTS_CONTRAGENT>();
        }
    
        public int CGNT_ID { get; set; }
        public string CGNT_NAME { get; set; }
        public Nullable<decimal> CGNT_INN { get; set; }
        public Nullable<decimal> CGNT_KPP { get; set; }
        public Nullable<System.Guid> CGNT_FIN_ID { get; set; }
        public int CUN_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGNT_BILL> CGNT_BILL { get; set; }
        public virtual CGNT_FIN_UNIT CGNT_FIN_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS_CONTRAGENT> CL_CLIENTS_CONTRAGENT { get; set; }
    }
}
