//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGNT_BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGNT_BILL()
        {
            this.CGNT_BILL_ITEM = new HashSet<CGNT_BILL_ITEM>();
        }
    
        public int BL_ID { get; set; }
        public string BL_NUM { get; set; }
        public int CGNT_ID { get; set; }
        public Nullable<System.DateTime> BL_DATE { get; set; }
        public Nullable<decimal> BL_SUM { get; set; }
        public Nullable<System.Guid> BL_FIN_ID { get; set; }
        public Nullable<decimal> BL_TAX_SUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGNT_BILL_ITEM> CGNT_BILL_ITEM { get; set; }
        public virtual CGNT_CONTRAGENT CGNT_CONTRAGENT { get; set; }
    }
}
