//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ACTUAL_CONFIGURATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_ACTUAL_CONFIGURATIONS()
        {
            this.CL_ACTUAL_SETTINGS = new HashSet<CL_ACTUAL_SETTINGS>();
        }
    
        public decimal CAC_ID { get; set; }
        public decimal OACT_ID { get; set; }
        public decimal OACV_ID { get; set; }
        public bool CAC_IS_DEFAULT { get; set; }
    
        public virtual OPT_ACTUAL_COEF_TYPES OPT_ACTUAL_COEF_TYPES { get; set; }
        public virtual OPT_ACTUAL_COEF_VALUES OPT_ACTUAL_COEF_VALUES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_ACTUAL_SETTINGS> CL_ACTUAL_SETTINGS { get; set; }
    }
}
