//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ACTUAL_SETTINGS
    {
        public decimal CAS_ID { get; set; }
        public decimal CAST_ID { get; set; }
        public decimal CL_ID { get; set; }
        public decimal CAC_ID { get; set; }
    
        public virtual CL_ACTUAL_CONFIGURATIONS CL_ACTUAL_CONFIGURATIONS { get; set; }
        public virtual CL_ACTUAL_SETTINGS_TRANSACTIONS CL_ACTUAL_SETTINGS_TRANSACTIONS { get; set; }
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
    }
}
