//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ACTUAL_SETTINGS_TRANSACTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_ACTUAL_SETTINGS_TRANSACTIONS()
        {
            this.CL_ACTUAL_SETTINGS = new HashSet<CL_ACTUAL_SETTINGS>();
        }
    
        public decimal CAST_ID { get; set; }
        public decimal US_ID { get; set; }
        public decimal CATT_ID { get; set; }
        public System.DateTime CAST_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_ACTUAL_SETTINGS> CL_ACTUAL_SETTINGS { get; set; }
        public virtual CL_ACTUAL_SETTINGS_TRANSACTIONS_TYPES CL_ACTUAL_SETTINGS_TRANSACTIONS_TYPES { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
