//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ACTUAL_SETTINGS_TRANSACTIONS_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_ACTUAL_SETTINGS_TRANSACTIONS_TYPES()
        {
            this.CL_ACTUAL_SETTINGS_TRANSACTIONS = new HashSet<CL_ACTUAL_SETTINGS_TRANSACTIONS>();
        }
    
        public decimal CATT_ID { get; set; }
        public string CATT_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_ACTUAL_SETTINGS_TRANSACTIONS> CL_ACTUAL_SETTINGS_TRANSACTIONS { get; set; }
    }
}
