//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_BLACKLIST
    {
        public decimal CL_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public string CLBL_COMMENT { get; set; }
        public System.DateTime CLBL_ADDED { get; set; }
        public decimal US_ID { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
