//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CLIENTS_USERS
    {
        public decimal CL_ID { get; set; }
        public decimal US_ID { get; set; }
        public bool CCU_EDIT { get; set; }
        public bool CCU_RESPONSIVE { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
