//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_CONTRACT()
        {
            this.CL_CONTRACT_ITEM = new HashSet<CL_CONTRACT_ITEM>();
            this.CL_CONTRACT1 = new HashSet<CL_CONTRACT>();
            this.INV_INVOICE = new HashSet<INV_INVOICE>();
            this.LE_OBLIGATION = new HashSet<LE_OBLIGATION>();
            this.OR_ORDER_HISTORY = new HashSet<OR_ORDER_HISTORY>();
        }
    
        public int CON_ID { get; set; }
        public Nullable<int> CON_MASTER_ID { get; set; }
        public int CLJN_ID { get; set; }
        public string CON_NUMBER { get; set; }
        public System.DateTime CON_DATE_FROM { get; set; }
        public System.DateTime CON_DATE_TO { get; set; }
        public decimal CON_MIN_DURATION { get; set; }
        public System.DateTime CON_DATE { get; set; }
        public string CON_SIGNATORY { get; set; }
        public decimal RP_SIGNATORY { get; set; }
        public byte[] CON_DATA { get; set; }
        public string CON_DATA_EXT { get; set; }
        public decimal US_ADDED { get; set; }
        public System.DateTime DATE_ADDED { get; set; }
        public bool IS_MISTAKEN { get; set; }
        public int INNER_CLJN_ID { get; set; }
    
        public virtual CL_JURI_NAMES CL_JURI_NAMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT_ITEM> CL_CONTRACT_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT> CL_CONTRACT1 { get; set; }
        public virtual CL_CONTRACT CL_CONTRACT2 { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual SC_USERS SC_USERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_INVOICE> INV_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LE_OBLIGATION> LE_OBLIGATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_HISTORY> OR_ORDER_HISTORY { get; set; }
    }
}
