//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CONTRACT_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_CONTRACT_ITEM()
        {
            this.CL_CONTRACT_ITEM1 = new HashSet<CL_CONTRACT_ITEM>();
            this.CL_RATE = new HashSet<CL_RATE>();
        }
    
        public int CCI_ID { get; set; }
        public Nullable<int> CCI_MASTER_ID { get; set; }
        public int CON_ID { get; set; }
        public int CCWT_ID { get; set; }
        public string CCI_NAME { get; set; }
        public decimal CCI_SUM { get; set; }
    
        public virtual CL_CONTRACT CL_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT_ITEM> CL_CONTRACT_ITEM1 { get; set; }
        public virtual CL_CONTRACT_ITEM CL_CONTRACT_ITEM2 { get; set; }
        public virtual CL_CONTRACT_WORK_TYPE CL_CONTRACT_WORK_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_RATE> CL_RATE { get; set; }
    }
}
