//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CONTRACT_WORK_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_CONTRACT_WORK_TYPE()
        {
            this.CL_CONTRACT_ITEM = new HashSet<CL_CONTRACT_ITEM>();
        }
    
        public int CCWT_ID { get; set; }
        public int CJNN_ID { get; set; }
        public string WT_NAME { get; set; }
        public string CL_WT_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT_ITEM> CL_CONTRACT_ITEM { get; set; }
        public virtual CL_JURI_NETS CL_JURI_NETS { get; set; }
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
    }
}
