//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_CLIENTS()
        {
            this.CL_ACTUAL_SETTINGS = new HashSet<CL_ACTUAL_SETTINGS>();
            this.CL_BLACKLIST = new HashSet<CL_BLACKLIST>();
            this.CL_CLIENTS_USERS = new HashSet<CL_CLIENTS_USERS>();
            this.CL_CLIENTS_CONTRAGENT = new HashSet<CL_CLIENTS_CONTRAGENT>();
            this.CL_RANGE_REQUIREMENTS = new HashSet<CL_RANGE_REQUIREMENTS>();
            this.CL_RATE = new HashSet<CL_RATE>();
            this.CL_WR_WAGE = new HashSet<CL_WR_WAGE>();
            this.CGN_BONUS_CLIENTS = new HashSet<CGN_BONUS_CLIENTS>();
            this.CL_CLIENTS_NETS_DEPARTEMNTS = new HashSet<CL_CLIENTS_NETS_DEPARTEMNTS>();
            this.CL_SUPERVISORS = new HashSet<CL_SUPERVISORS>();
            this.GREEN_LIST = new HashSet<GREEN_LIST>();
            this.CL_CONTACTS = new HashSet<CL_CONTACTS>();
            this.OR_ORDER = new HashSet<OR_ORDER>();
            this.CL_WORK_COSTS = new HashSet<CL_WORK_COSTS>();
            this.CL_CLIENTS1 = new HashSet<CL_CLIENTS>();
            this.CL_CLIENTS2 = new HashSet<CL_CLIENTS>();
        }
    
        public decimal CL_ID { get; set; }
        public string CL_NAME { get; set; }
        public string CL_ADDRESS { get; set; }
        public string CL_PHONE { get; set; }
        public string CL_INFO { get; set; }
        public Nullable<decimal> NT_ID { get; set; }
        public string CL_SITE { get; set; }
        public Nullable<System.DateTime> CL_DATEADD { get; set; }
        public Nullable<bool> IS_DINNER_BONUS { get; set; }
        public decimal CL_POSITION_LAT { get; set; }
        public decimal CL_POSITION_LNG { get; set; }
        public decimal UN_ID { get; set; }
        public string CL_EMAIL { get; set; }
        public Nullable<int> CLJN_ID { get; set; }
        public Nullable<decimal> CL_PERMANENTW_PERCENT { get; set; }
        public string CL_HOW_TO_GET { get; set; }
        public decimal CL_PRIORITY { get; set; }
        public bool CL_IS_TECHNICAL { get; set; }
        public string CL_SMS_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_ACTUAL_SETTINGS> CL_ACTUAL_SETTINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_BLACKLIST> CL_BLACKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS_USERS> CL_CLIENTS_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS_CONTRAGENT> CL_CLIENTS_CONTRAGENT { get; set; }
        public virtual CL_PRIORITY CL_PRIORITY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_RANGE_REQUIREMENTS> CL_RANGE_REQUIREMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_RATE> CL_RATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_WR_WAGE> CL_WR_WAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGN_BONUS_CLIENTS> CGN_BONUS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS_NETS_DEPARTEMNTS> CL_CLIENTS_NETS_DEPARTEMNTS { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
        public virtual CL_MAIL_TEMPLATES CL_MAIL_TEMPLATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_SUPERVISORS> CL_SUPERVISORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GREEN_LIST> GREEN_LIST { get; set; }
        public virtual CL_NETS CL_NETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTACTS> CL_CONTACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER> OR_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_WORK_COSTS> CL_WORK_COSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS> CL_CLIENTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS> CL_CLIENTS2 { get; set; }
    }
}
