//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CLIENTS_NETS_DEPARTEMNTS
    {
        public decimal CND_ID { get; set; }
        public decimal CL_ID { get; set; }
        public decimal ND_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual CL_NETS_DEPARTMENTS CL_NETS_DEPARTMENTS { get; set; }
    }
}
