//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CONTACTS
    {
        public decimal CN_ID { get; set; }
        public string CN_NAME { get; set; }
        public string CN_CONTACT { get; set; }
        public decimal CL_ID { get; set; }
        public string CN_PHONE_2 { get; set; }
        public string CN_PHONE_MOBILE { get; set; }
        public string CN_MOBILE_2 { get; set; }
        public string CN_EMAIL { get; set; }
        public string CN_POST { get; set; }
        public string CN_COMMENT { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
    }
}
