//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_CLIENTS_CONTRAGENT
    {
        public int CCGNT_ID { get; set; }
        public decimal CL_ID { get; set; }
        public int CGNT_ID { get; set; }
    
        public virtual CGNT_CONTRAGENT CGNT_CONTRAGENT { get; set; }
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
    }
}
