//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_JURI_NAMES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_JURI_NAMES()
        {
            this.CL_CONTRACT = new HashSet<CL_CONTRACT>();
            this.LE_SIGN = new HashSet<LE_SIGN>();
            this.CL_JURI_NAMES_EXTENSIONS = new HashSet<CL_JURI_NAMES_EXTENSIONS>();
            this.CL_JURI_NETS = new HashSet<CL_JURI_NETS>();
        }
    
        public int CLJN_ID { get; set; }
        public string CLJN_NAME { get; set; }
        public string CLJN_ORGANIZATION_TYPE { get; set; }
        public string CLJN_SHORT_NAME { get; set; }
        public string CLJN_ADDRESS { get; set; }
        public string CLJN_INN { get; set; }
        public string CLJN_KPP { get; set; }
        public string CLJN_CURRENT_ACCOUNT { get; set; }
        public string CLJN_OFFSETING_ACCOUNT { get; set; }
        public string CLJN_BANK { get; set; }
        public string CLJN_BIC { get; set; }
        public string CLJN_SIGNATORY { get; set; }
        public bool IS_INNER { get; set; }
        public string CLJN_PHONE_NUMBERS { get; set; }
        public int TAX_TYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT> CL_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LE_SIGN> LE_SIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JURI_NAMES_EXTENSIONS> CL_JURI_NAMES_EXTENSIONS { get; set; }
        public virtual CL_LEGAL_ENTITY_TAXATION_TYPES CL_LEGAL_ENTITY_TAXATION_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JURI_NETS> CL_JURI_NETS { get; set; }
    }
}
