//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_JURI_NETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_JURI_NETS()
        {
            this.CL_CONTRACT_WORK_TYPE = new HashSet<CL_CONTRACT_WORK_TYPE>();
        }
    
        public Nullable<int> CLJN_ID { get; set; }
        public decimal NT_ID { get; set; }
        public int CJNN_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT_WORK_TYPE> CL_CONTRACT_WORK_TYPE { get; set; }
        public virtual CL_JURI_NAMES CL_JURI_NAMES { get; set; }
        public virtual CL_NETS CL_NETS { get; set; }
    }
}
