//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_LEGAL_ENTITY_TAXATION_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_LEGAL_ENTITY_TAXATION_TYPES()
        {
            this.CL_JURI_NAMES = new HashSet<CL_JURI_NAMES>();
        }
    
        public int TAX_TYPE_ID { get; set; }
        public string CAPTION { get; set; }
        public string KEYCHAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JURI_NAMES> CL_JURI_NAMES { get; set; }
    }
}
