//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_MAIL_TEMPLATES
    {
        public decimal CL_ID { get; set; }
        public string CLMT_BODY { get; set; }
        public string CLMT_LINE { get; set; }
        public bool CLMT_MED_BOOK { get; set; }
        public bool CLMT_PASSPORT { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
    }
}
