//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_NETS_DEPARTMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_NETS_DEPARTMENTS()
        {
            this.CL_CLIENTS_NETS_DEPARTEMNTS = new HashSet<CL_CLIENTS_NETS_DEPARTEMNTS>();
        }
    
        public decimal ND_ID { get; set; }
        public decimal NT_ID { get; set; }
        public decimal DEP_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS_NETS_DEPARTEMNTS> CL_CLIENTS_NETS_DEPARTEMNTS { get; set; }
        public virtual CL_DEPARTMENTS CL_DEPARTMENTS { get; set; }
        public virtual CL_NETS CL_NETS { get; set; }
    }
}
