//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_NETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CL_NETS()
        {
            this.CL_CLIENTS = new HashSet<CL_CLIENTS>();
            this.CL_JURI_NETS = new HashSet<CL_JURI_NETS>();
            this.NT_BLACKLIST = new HashSet<NT_BLACKLIST>();
            this.NT_RANGE_REQUIREMENTS = new HashSet<NT_RANGE_REQUIREMENTS>();
            this.CL_NETS_DEPARTMENTS = new HashSet<CL_NETS_DEPARTMENTS>();
        }
    
        public decimal NT_ID { get; set; }
        public string NT_NAME { get; set; }
        public Nullable<bool> NT_BY_DEFAULT { get; set; }
    
        public virtual CGN_BONUS_OPTIONS CGN_BONUS_OPTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS> CL_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JURI_NETS> CL_JURI_NETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NT_BLACKLIST> NT_BLACKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NT_RANGE_REQUIREMENTS> NT_RANGE_REQUIREMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_NETS_DEPARTMENTS> CL_NETS_DEPARTMENTS { get; set; }
    }
}
