//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_RANGE_REQUIREMENTS
    {
        public decimal CL_ID { get; set; }
        public string WT_NAME { get; set; }
        public int RR_ID { get; set; }
        public Nullable<int> CL_RR_MIN { get; set; }
        public Nullable<int> CL_RR_MAX { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual OPT_RANGE_REFERENCES OPT_RANGE_REFERENCES { get; set; }
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
    }
}
