//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_SUPERVISORS
    {
        public decimal SCU_ID { get; set; }
        public decimal CL_ID { get; set; }
        public bool CLS_IS_RESPONSIVE { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual WR_SUPERVISORS WR_SUPERVISORS { get; set; }
    }
}
