//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_WR_WAGE
    {
        public int CWR_ID { get; set; }
        public decimal CL_ID { get; set; }
        public int WRW_ID { get; set; }
        public System.DateTime DATE_START { get; set; }
        public System.DateTime DATE_END { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual WR_WAGES WR_WAGES { get; set; }
    }
}
