//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_WORK_COSTS
    {
        public string WT_NAME { get; set; }
        public decimal CL_ID { get; set; }
        public decimal CWC_NUM { get; set; }
        public string CWC_DOC_NUM { get; set; }
        public Nullable<System.DateTime> CWC_START { get; set; }
        public Nullable<System.DateTime> CWC_END { get; set; }
        public Nullable<decimal> CWC_COST_HUMAN_HOUR { get; set; }
        public string WT_NAME_IN_DEAL { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
    }
}
