//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRE_MACHINE_HISTORY
    {
        public decimal FMH_ID { get; set; }
        public System.DateTime DATE_INSERT { get; set; }
        public int REASON_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public decimal FM_ID { get; set; }
    
        public virtual FIRE_MACHINE FIRE_MACHINE { get; set; }
        public virtual REASONS_FIRE_MACHINE REASONS_FIRE_MACHINE { get; set; }
    }
}
