//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUN_MAGIC_BUTTON
    {
        public decimal US_ID { get; set; }
        public decimal FMB_CLICK { get; set; }
        public System.DateTime FMB_CLICK_TIME { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
