//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GREEN_LIST_HISTORY
    {
        public decimal GLH_ID { get; set; }
        public string REASON { get; set; }
        public string COMMENT { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime DATE_INSERT { get; set; }
        public decimal GL_ID { get; set; }
    
        public virtual GREEN_LIST GREEN_LIST { get; set; }
    }
}
