//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GREEN_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GREEN_LIST()
        {
            this.GREEN_LIST_HISTORY = new HashSet<GREEN_LIST_HISTORY>();
        }
    
        public decimal GL_ID { get; set; }
        public decimal CL_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GREEN_LIST_HISTORY> GREEN_LIST_HISTORY { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
