//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_ITEM()
        {
            this.INV_ITEM_WORKER = new HashSet<INV_ITEM_WORKER>();
            this.INV_ITEM_ORDER = new HashSet<INV_ITEM_ORDER>();
            this.INV_ITEM_LEGAL_ENTITY = new HashSet<INV_ITEM_LEGAL_ENTITY>();
        }
    
        public int INV_ITEM_ID { get; set; }
        public int INV_ID { get; set; }
        public int INV_ITEM_TYPE_ID { get; set; }
    
        public virtual INV_INVOICE INV_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEM_WORKER> INV_ITEM_WORKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEM_ORDER> INV_ITEM_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEM_LEGAL_ENTITY> INV_ITEM_LEGAL_ENTITY { get; set; }
        public virtual INV_ITEM_TYPE INV_ITEM_TYPE { get; set; }
    }
}
