//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_INVOICE()
        {
            this.INV_HISTORY = new HashSet<INV_HISTORY>();
            this.INV_ITEM = new HashSet<INV_ITEM>();
            this.INV_SIGN = new HashSet<INV_SIGN>();
            this.INV_SENT_EMAILS = new HashSet<INV_SENT_EMAILS>();
        }
    
        public int INV_ID { get; set; }
        public string INV_NUM { get; set; }
        public int CON_ID { get; set; }
        public System.DateTime INV_DATE { get; set; }
        public decimal US_ID { get; set; }
        public decimal INV_SUM { get; set; }
        public decimal INV_VAT { get; set; }
        public decimal INV_TAX { get; set; }
        public System.DateTime DATE_FROM { get; set; }
        public System.DateTime DATE_TO { get; set; }
        public string Filters { get; set; }
    
        public virtual CL_CONTRACT CL_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_HISTORY> INV_HISTORY { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEM> INV_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SIGN> INV_SIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SENT_EMAILS> INV_SENT_EMAILS { get; set; }
    }
}
