//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ITEM_WORKER
    {
        public int IIW_ID { get; set; }
        public int INV_ITEM_ID { get; set; }
        public int OOWH_ID { get; set; }
    
        public virtual INV_ITEM INV_ITEM { get; set; }
        public virtual OR_ORDER_WORKER_HISTORY OR_ORDER_WORKER_HISTORY { get; set; }
    }
}
