//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_SENT_EMAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_SENT_EMAILS()
        {
            this.INV_INVOICE = new HashSet<INV_INVOICE>();
        }
    
        public int EMAIL_ID { get; set; }
        public decimal FROM_US_ID { get; set; }
        public decimal TO_US_ID { get; set; }
        public System.DateTime SENT_DATE { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual SC_USERS SC_USERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_INVOICE> INV_INVOICE { get; set; }
    }
}
