//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LE_OBLIGATION_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LE_OBLIGATION_HISTORY()
        {
            this.INV_ITEM_LEGAL_ENTITY = new HashSet<INV_ITEM_LEGAL_ENTITY>();
        }
    
        public int LEOH_ID { get; set; }
        public int LEO_ID { get; set; }
        public System.DateTime EDIT_TIME { get; set; }
        public decimal US_ID { get; set; }
        public string LEOH_COMMENT { get; set; }
        public byte[] LEOH_DATA { get; set; }
        public string LEOH_DATA_EXT { get; set; }
        public bool IS_ACCEPTED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEM_LEGAL_ENTITY> INV_ITEM_LEGAL_ENTITY { get; set; }
        public virtual LE_OBLIGATION LE_OBLIGATION { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
