//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_USERS_ACTS
    {
        public decimal US_ID { get; set; }
        public System.DateTime ACTION_TIME { get; set; }
        public decimal ACTION_TYPE { get; set; }
        public Nullable<decimal> UN_ID { get; set; }
        public Nullable<decimal> WR_ID { get; set; }
        public Nullable<decimal> OR_ID { get; set; }
        public string AC_COMMENT { get; set; }
    }
}
