//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_CC_IN_OUT
    {
        public decimal LCIO_ID { get; set; }
        public decimal US_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal OR_ID { get; set; }
        public decimal LCIO_TYPE { get; set; }
        public System.DateTime LCIO_DATETIME { get; set; }
        public decimal LCIO_BLOCK_SECONDS { get; set; }
    
        public virtual WR_WORKERS WR_WORKERS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
