//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NT_BLACKLIST
    {
        public decimal NT_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public string NTBL_COMMENT { get; set; }
        public System.DateTime NTBL_ADDED { get; set; }
        public Nullable<decimal> US_ID { get; set; }
    
        public virtual CL_NETS CL_NETS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
