//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_CHARGE_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_CHARGE_GROUP()
        {
            this.OPT_PENALTY_TYPES = new HashSet<OPT_PENALTY_TYPES>();
        }
    
        public byte OCG_ID { get; set; }
        public string OCG_NAME { get; set; }
        public string OCG_KEYCHAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_PENALTY_TYPES> OPT_PENALTY_TYPES { get; set; }
    }
}
