//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_ATTRIBUTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_ATTRIBUTES()
        {
            this.OPT_DOC_TYPES_ATTRS = new HashSet<OPT_DOC_TYPES_ATTRS>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string KEY_CHAR_VAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_DOC_TYPES_ATTRS> OPT_DOC_TYPES_ATTRS { get; set; }
    }
}
