//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_DISMISSAL_ITEM_COST
    {
        public int ODIC_ID { get; set; }
        public Nullable<int> OPTD_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal COST { get; set; }
        public int SHIFT_COUNT { get; set; }
        public System.DateTime DATE_START { get; set; }
        public System.DateTime DATE_END { get; set; }
    
        public virtual OPT_DISMISSAL_ITEMS OPT_DISMISSAL_ITEMS { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
