//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_ACTION_BONUSES_20x100
    {
        public decimal UN_ID { get; set; }
        public decimal ACT_BONUS_SUM { get; set; }
        public decimal ACT_ATTENDANCE_COUNT { get; set; }
    }
}
