//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_REFERENCES_CHECK_SEQURITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_REFERENCES_CHECK_SEQURITY()
        {
            this.OPT_REFERENCES_UNIT = new HashSet<OPT_REFERENCES_UNIT>();
        }
    
        public int ORS_ID { get; set; }
        public bool IS_SHOULD_BE_CHECKED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_REFERENCES_UNIT> OPT_REFERENCES_UNIT { get; set; }
    }
}
