//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_SMS_TEMPLATES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_SMS_TEMPLATES()
        {
            this.OPT_REGIONAL_SMS = new HashSet<OPT_REGIONAL_SMS>();
            this.SC_PLACES_SMS = new HashSet<SC_PLACES_SMS>();
        }
    
        public int OSMST_ID { get; set; }
        public string OSMST_TEXT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_REGIONAL_SMS> OPT_REGIONAL_SMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SC_PLACES_SMS> SC_PLACES_SMS { get; set; }
    }
}
