//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_FIN_WORK_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_FIN_WORK_TYPES()
        {
            this.CGNT_BILL_ITEM = new HashSet<CGNT_BILL_ITEM>();
            this.OPT_FIN_BDP_WORK_TYPES = new HashSet<OPT_FIN_BDP_WORK_TYPES>();
        }
    
        public int FWT_ID { get; set; }
        public string FWT_NAME { get; set; }
        public Nullable<System.Guid> FWT_FIN_ID { get; set; }
        public string FWT_UNIT_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGNT_BILL_ITEM> CGNT_BILL_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_FIN_BDP_WORK_TYPES> OPT_FIN_BDP_WORK_TYPES { get; set; }
    }
}
