//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_REGIONAL_PENALTY_COSTS
    {
        public decimal UN_ID { get; set; }
        public decimal PEN_TYPE_ID { get; set; }
        public decimal WR_COST { get; set; }
        public int PEN_COUNT { get; set; }
        public System.DateTime DATE_FROM { get; set; }
        public System.DateTime DATE_TO { get; set; }
        public int RPC_ID { get; set; }
    
        public virtual OPT_PENALTY_TYPES OPT_PENALTY_TYPES { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
