//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_KEEPING_UNITS
    {
        public int ID { get; set; }
        public decimal KP_ID { get; set; }
        public decimal UN_ID { get; set; }
    
        public virtual OPT_KEEPING OPT_KEEPING { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
