//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_STATUSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_STATUSES()
        {
            this.WR_HISTORY = new HashSet<WR_HISTORY>();
            this.OPT_OPTIONS = new HashSet<OPT_OPTIONS>();
            this.WR_WORKERS = new HashSet<WR_WORKERS>();
        }
    
        public decimal ST_ID { get; set; }
        public string ST_NAME { get; set; }
        public Nullable<decimal> ST_SORT_ORDER { get; set; }
        public Nullable<decimal> CHANGE_STAT_WORKED_DAYS { get; set; }
        public Nullable<decimal> CHANGE_STAT_WORKED_PERIOD { get; set; }
        public bool ST_IS_DISMISSAL { get; set; }
        public bool ST_IS_DISMISSAL_BY_COMPANY { get; set; }
        public bool ST_IS_DISMISSAL_BY_SECSERV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_HISTORY> WR_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_OPTIONS> OPT_OPTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKERS> WR_WORKERS { get; set; }
    }
}
