//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_ACTUAL_COEF_VALUES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_ACTUAL_COEF_VALUES()
        {
            this.CL_ACTUAL_CONFIGURATIONS = new HashSet<CL_ACTUAL_CONFIGURATIONS>();
        }
    
        public decimal OACV_ID { get; set; }
        public int OACV_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_ACTUAL_CONFIGURATIONS> CL_ACTUAL_CONFIGURATIONS { get; set; }
    }
}
