//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_REGIONAL_SMS
    {
        public decimal UN_ID { get; set; }
        public int OSMST_ID { get; set; }
        public bool IsActive { get; set; }
        public string OverrideText { get; set; }
    
        public virtual OPT_SMS_TEMPLATES OPT_SMS_TEMPLATES { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
