//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_DOC_STATE_ATTRIBUTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_DOC_STATE_ATTRIBUTES()
        {
            this.WR_WORKER_DOCS_ATTRIBUTES = new HashSet<WR_WORKER_DOCS_ATTRIBUTES>();
        }
    
        public decimal ID { get; set; }
        public decimal DOC_STATE_ID { get; set; }
        public decimal DOC_ATTR_ID { get; set; }
    
        public virtual OPT_DOCS_STATES OPT_DOCS_STATES { get; set; }
        public virtual OPT_DOC_TYPES_ATTRS OPT_DOC_TYPES_ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_DOCS_ATTRIBUTES> WR_WORKER_DOCS_ATTRIBUTES { get; set; }
    }
}
