//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_BONUS_NAMES
    {
        public decimal OBN_ID { get; set; }
        public string OBN_NAME { get; set; }
        public bool IS_DINNER { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
