//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_INFO_SITES
    {
        public decimal OIS_ID { get; set; }
        public string OIS_SITE_NAME { get; set; }
        public bool OIS_IS_PARENT { get; set; }
        public decimal OIS_PARENT_ID { get; set; }
        public bool OIS_SHOW { get; set; }
        public decimal UN_ID { get; set; }
    
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
