//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_CH_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_CH_ITEM()
        {
            this.WR_CH_CARD_ITEM = new HashSet<WR_CH_CARD_ITEM>();
        }
    
        public int CH_IT_ID { get; set; }
        public Nullable<int> CH_ID { get; set; }
        public string CH_IT_NAME { get; set; }
        public int CH_IT_VALUE { get; set; }
    
        public virtual OPT_CHARACTERISTIC OPT_CHARACTERISTIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_CH_CARD_ITEM> WR_CH_CARD_ITEM { get; set; }
    }
}
