//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_FIN_BDP_WORK_TYPES
    {
        public int FBWT_ID { get; set; }
        public int FWT_ID { get; set; }
        public string WT_ID { get; set; }
    
        public virtual OPT_FIN_WORK_TYPES OPT_FIN_WORK_TYPES { get; set; }
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
    }
}
