//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_BANK_CARDS
    {
        public decimal ID { get; set; }
        public decimal AB_ID { get; set; }
        public string BANK_CARD_ID { get; set; }
        public string CARD_NUMBER { get; set; }
        public string CARD_ACCOUNT_NUMBER { get; set; }
        public Nullable<System.DateTime> VALID_UNTIL { get; set; }
        public string CITY { get; set; }
    
        public virtual AC_BANKS AC_BANKS { get; set; }
    }
}
