//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_REFERENCES_UNIT
    {
        public int ORU_ID { get; set; }
        public decimal REF_ID { get; set; }
        public decimal UN_ID { get; set; }
        public int RUS_ID { get; set; }
    
        public virtual OPT_REFERENCES OPT_REFERENCES { get; set; }
        public virtual OPT_REFERENCES_CHECK_SEQURITY OPT_REFERENCES_CHECK_SEQURITY { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
