//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_SHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_SHEDULE()
        {
            this.WR_SHEDULE_ITEM = new HashSet<WR_SHEDULE_ITEM>();
        }
    
        public int Id { get; set; }
        public int IsSheduleType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual OPT_SHEDULE_TYPE OPT_SHEDULE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_SHEDULE_ITEM> WR_SHEDULE_ITEM { get; set; }
    }
}
