//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_WAGE_OPTIONS_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_WAGE_OPTIONS_TYPE()
        {
            this.WR_WAGES_OPTIONS = new HashSet<WR_WAGES_OPTIONS>();
        }
    
        public int ID { get; set; }
        public string TYPE_NAME { get; set; }
        public string KEYCHAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WAGES_OPTIONS> WR_WAGES_OPTIONS { get; set; }
    }
}
