//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_TEL_CODE_ZONES
    {
        public string OTCZ_TEL_CODE { get; set; }
        public decimal OTCZ_UNIT { get; set; }
    
        public virtual SC_UNIT SC_UNIT { get; set; }
    }
}
