//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_DOC_TYPES_ATTRS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_DOC_TYPES_ATTRS()
        {
            this.OPT_DOC_STATE_ATTRIBUTES = new HashSet<OPT_DOC_STATE_ATTRIBUTES>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_DOC_TYPE { get; set; }
        public decimal ID_ATTR { get; set; }
    
        public virtual OPT_ATTRIBUTES OPT_ATTRIBUTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_DOC_STATE_ATTRIBUTES> OPT_DOC_STATE_ATTRIBUTES { get; set; }
        public virtual OPT_DOCUMENT_TYPES OPT_DOCUMENT_TYPES { get; set; }
    }
}
