//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_IMG_NAMES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_IMG_NAMES()
        {
            this.WR_IMAGES = new HashSet<WR_IMAGES>();
        }
    
        public decimal IN_ID { get; set; }
        public string IN_NAME { get; set; }
        public bool IN_IS_PASSPORT { get; set; }
        public bool IN_IS_SIGNATURE { get; set; }
        public bool IN_IS_REGISTRATION { get; set; }
        public bool IN_IS_WORK_RECORD_CARD { get; set; }
        public bool IN_IS_INN { get; set; }
        public bool IN_IS_INSURANCE { get; set; }
        public bool IN_IS_MILITARY_CARD { get; set; }
        public bool IN_IS_DIPLOMA { get; set; }
        public bool IN_IS_MEDICAL_CARD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_IMAGES> WR_IMAGES { get; set; }
    }
}
