//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_DISMISSAL_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_DISMISSAL_ITEMS()
        {
            this.OPT_DISMISSAL_ITEM_COST = new HashSet<OPT_DISMISSAL_ITEM_COST>();
            this.WR_DISMISSAL_ITEMS = new HashSet<WR_DISMISSAL_ITEMS>();
        }
    
        public string OPTD_NAME { get; set; }
        public int OPTD_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_DISMISSAL_ITEM_COST> OPT_DISMISSAL_ITEM_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_DISMISSAL_ITEMS> WR_DISMISSAL_ITEMS { get; set; }
    }
}
