//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_RANGE_REFERENCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_RANGE_REFERENCES()
        {
            this.CL_RANGE_REQUIREMENTS = new HashSet<CL_RANGE_REQUIREMENTS>();
            this.NT_RANGE_REQUIREMENTS = new HashSet<NT_RANGE_REQUIREMENTS>();
            this.OR_RANGE_REQUIREMENTS = new HashSet<OR_RANGE_REQUIREMENTS>();
        }
    
        public int RR_ID { get; set; }
        public string RR_NAME { get; set; }
        public int RR_VALUE { get; set; }
        public Nullable<int> RR_MIN { get; set; }
        public Nullable<int> RR_MAX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_RANGE_REQUIREMENTS> CL_RANGE_REQUIREMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NT_RANGE_REQUIREMENTS> NT_RANGE_REQUIREMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_RANGE_REQUIREMENTS> OR_RANGE_REQUIREMENTS { get; set; }
    }
}
