//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_STATUS()
        {
            this.INV_HISTORY = new HashSet<INV_HISTORY>();
            this.OR_ORDER_HISTORY = new HashSet<OR_ORDER_HISTORY>();
            this.WR_DISMISSAL_ITEMS_HISTORY = new HashSet<WR_DISMISSAL_ITEMS_HISTORY>();
        }
    
        public int STATUS_ID { get; set; }
        public int STATUS_GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string KEYCHAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_HISTORY> INV_HISTORY { get; set; }
        public virtual OPT_STATUS_GROUP OPT_STATUS_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_HISTORY> OR_ORDER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_DISMISSAL_ITEMS_HISTORY> WR_DISMISSAL_ITEMS_HISTORY { get; set; }
    }
}
