//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_DOCS_STATES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_DOCS_STATES()
        {
            this.OPT_DOC_STATE_ATTRIBUTES = new HashSet<OPT_DOC_STATE_ATTRIBUTES>();
            this.WR_WORKER_DOCUMENTS = new HashSet<WR_WORKER_DOCUMENTS>();
        }
    
        public decimal ID { get; set; }
        public decimal DOC_TYPE_ID { get; set; }
        public decimal STATE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_DOC_STATE_ATTRIBUTES> OPT_DOC_STATE_ATTRIBUTES { get; set; }
        public virtual OPT_DOCUMENT_TYPES OPT_DOCUMENT_TYPES { get; set; }
        public virtual WR_KLADR_COUNTRIES WR_KLADR_COUNTRIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_DOCUMENTS> WR_WORKER_DOCUMENTS { get; set; }
    }
}
