//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_REGIONAL_SPECIFICS
    {
        public decimal UN_ID { get; set; }
        public decimal OPT_ID { get; set; }
        public string OPT_NAME { get; set; }
        public string GENITIVE { get; set; }
    }
}
