//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_PENALTY_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_PENALTY_TYPES()
        {
            this.OPT_LATERS = new HashSet<OPT_LATERS>();
            this.OPT_REGIONAL_PENALTY_COSTS = new HashSet<OPT_REGIONAL_PENALTY_COSTS>();
            this.WR_CHARGE = new HashSet<WR_CHARGE>();
            this.OPT_RELATIONSHIP_PENALTY_TYPES = new HashSet<OPT_RELATIONSHIP_PENALTY_TYPES>();
            this.OPT_RELATIONSHIP_PENALTY_TYPES1 = new HashSet<OPT_RELATIONSHIP_PENALTY_TYPES>();
            this.WR_PENALTIES = new HashSet<WR_PENALTIES>();
        }
    
        public decimal PEN_TYPE_ID { get; set; }
        public string WR_NAME { get; set; }
        public byte OCG_ID { get; set; }
    
        public virtual OPT_CHARGE_GROUP OPT_CHARGE_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_LATERS> OPT_LATERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_REGIONAL_PENALTY_COSTS> OPT_REGIONAL_PENALTY_COSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_CHARGE> WR_CHARGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_RELATIONSHIP_PENALTY_TYPES> OPT_RELATIONSHIP_PENALTY_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_RELATIONSHIP_PENALTY_TYPES> OPT_RELATIONSHIP_PENALTY_TYPES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_PENALTIES> WR_PENALTIES { get; set; }
    }
}
