//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_RELATIONSHIP_PENALTY_TYPES
    {
        public int OPT_RPT_ID { get; set; }
        public decimal PEN_TYPE_ID { get; set; }
        public decimal RELATIONSHIP_PEN_TYPE_ID { get; set; }
    
        public virtual OPT_PENALTY_TYPES OPT_PENALTY_TYPES { get; set; }
        public virtual OPT_PENALTY_TYPES OPT_PENALTY_TYPES1 { get; set; }
    }
}
