//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_OPTIONS
    {
        public Nullable<decimal> DEFAULT_STATUS { get; set; }
        public Nullable<decimal> MIN_DAYS_IN_CALC { get; set; }
        public Nullable<decimal> START_NUM_WORKERS { get; set; }
        public Nullable<decimal> START_NUM_USERS { get; set; }
        public Nullable<decimal> START_NUM_CLIENTS { get; set; }
        public Nullable<decimal> COUNT_NUM_UNIT_IN_BAGE { get; set; }
        public Nullable<decimal> COUNT_NUM_ID_IN_BAGE { get; set; }
        public Nullable<decimal> FILTER_DEF_COUNT_DAYS_WORKING_FROM_START { get; set; }
        public Nullable<decimal> FILTER_DEF_COUNT_DAYS_WORKING_TO_START { get; set; }
        public Nullable<decimal> FILTER_DEF_COUNT_DAYS_FROM_INSERT { get; set; }
        public Nullable<decimal> DEFAULT_CALL_AFTER_MINUTES { get; set; }
        public Nullable<decimal> MAX_CALL_AFTER_MON { get; set; }
        public Nullable<decimal> MAX_UPPER_WORK_PERS { get; set; }
        public Nullable<decimal> PAY_FOR_FRIEND { get; set; }
        public Nullable<decimal> COUNT_ORDERS_BY_FRIEND { get; set; }
        public Nullable<decimal> BONUS_RECRUTER_BY_HOUR { get; set; }
        public decimal MIN_REST { get; set; }
        public decimal PASSWORD_EXPIRE_DAYS { get; set; }
        public string SMS_ACTION_BRINGFRIEND_2012 { get; set; }
        public string SMS_ACTION_20x100 { get; set; }
        public string COVER_MAIL_TEMPLATE { get; set; }
        public string INV_STATUS_MAIL_BODY_TEMPLATE { get; set; }
    
        public virtual OPT_STATUSES OPT_STATUSES { get; set; }
    }
}
