//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPT_FILE_EXTENSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPT_FILE_EXTENSIONS()
        {
            this.WR_INTERNAL_CONTRACT = new HashSet<WR_INTERNAL_CONTRACT>();
        }
    
        public int Id { get; set; }
        public string EXTENSION_NAME { get; set; }
        public string MIME_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERNAL_CONTRACT> WR_INTERNAL_CONTRACT { get; set; }
    }
}
