//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ORDER_REQUIREMENTS
    {
        public decimal OR_ID { get; set; }
        public decimal OREQ_TYPE { get; set; }
        public decimal REF_ID { get; set; }
        public int ORR_ID { get; set; }
    }
}
