//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ORDER_WORKERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OR_ORDER_WORKERS()
        {
            this.ACTION_PAYMENTS = new HashSet<ACTION_PAYMENTS>();
            this.OR_ORDER_WORKER_HISTORY = new HashSet<OR_ORDER_WORKER_HISTORY>();
            this.CGN_CAMPAIGN = new HashSet<CGN_CAMPAIGN>();
        }
    
        public decimal OR_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public Nullable<System.DateTime> ORR_WORK_START { get; set; }
        public Nullable<System.DateTime> ORR_WORK_END { get; set; }
        public Nullable<decimal> ORR_COST_HUMAN_HOUR { get; set; }
        public Nullable<decimal> ORR_BONUS { get; set; }
        public Nullable<decimal> ORR_DEBONUS { get; set; }
        public Nullable<bool> ORR_IS_IN_ORDER_BY_DOC { get; set; }
        public Nullable<bool> ORR_IS_IN_ORDER_BY_REAL { get; set; }
        public Nullable<bool> ORR_IS_CALCULATED { get; set; }
        public string ORR_COMMENT { get; set; }
        public Nullable<decimal> ORR_COST_UNIT { get; set; }
        public decimal ORR_CLIENT_BONUS_HOURS { get; set; }
        public decimal ORR_DINNER_MINUTES { get; set; }
        public bool ORR_IS_CALL_COME { get; set; }
        public bool ORR_IS_CALL_LEAVE { get; set; }
        public System.DateTime ORR_WORKER_ADDED { get; set; }
        public decimal ORR_US_ID_ADD { get; set; }
        public bool ORR_FALSE_ALARM { get; set; }
        public decimal ORR_OUTPUT_TYPE { get; set; }
        public System.DateTime ORR_EXPECTED_TIME { get; set; }
        public bool ORR_MARK_ABSENT { get; set; }
        public bool OR_NEED_CHANGE { get; set; }
        public bool ORR_MARK_REMEMBER { get; set; }
        public string ORR_CC_FALSE_ALARM_COMMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTION_PAYMENTS> ACTION_PAYMENTS { get; set; }
        public virtual OPT_OUTPUT_TYPE OPT_OUTPUT_TYPE { get; set; }
        public virtual OR_ORDER OR_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_WORKER_HISTORY> OR_ORDER_WORKER_HISTORY { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
        public virtual OR_TRAIN_CENTER_WORKERS OR_TRAIN_CENTER_WORKERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGN_CAMPAIGN> CGN_CAMPAIGN { get; set; }
    }
}
