//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ORDER_COSTS_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OR_ORDER_COSTS_HISTORY()
        {
            this.INV_ITEM_ORDER = new HashSet<INV_ITEM_ORDER>();
        }
    
        public int OOCH_ID { get; set; }
        public int ORC_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime OOCH_DATE { get; set; }
        public string OOCH_COMMENT { get; set; }
        public byte[] OOCH_DATA { get; set; }
        public string OOCH_DATA_EXT { get; set; }
        public bool IS_ACCEPTED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEM_ORDER> INV_ITEM_ORDER { get; set; }
        public virtual OR_ORDER_COSTS OR_ORDER_COSTS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
