//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OR_ORDER()
        {
            this.CC_CALL_RESULTS = new HashSet<CC_CALL_RESULTS>();
            this.CC_IPTEL_LOGS = new HashSet<CC_IPTEL_LOGS>();
            this.CC_IPTEL_TASK_ORDER = new HashSet<CC_IPTEL_TASK_ORDER>();
            this.CC_WORKER_REMINDS = new HashSet<CC_WORKER_REMINDS>();
            this.OR_ORDER_COSTS = new HashSet<OR_ORDER_COSTS>();
            this.OR_ORDER_HISTORY = new HashSet<OR_ORDER_HISTORY>();
            this.OR_RANGE_REQUIREMENTS = new HashSet<OR_RANGE_REQUIREMENTS>();
            this.WR_RECRUITER_HISTORY = new HashSet<WR_RECRUITER_HISTORY>();
            this.OR_ORDER_COMMENTS = new HashSet<OR_ORDER_COMMENTS>();
            this.OR_PRE_ADD = new HashSet<OR_PRE_ADD>();
            this.OR_QUEUE_ACTUALISATION = new HashSet<OR_QUEUE_ACTUALISATION>();
            this.WR_ACTION_15x15 = new HashSet<WR_ACTION_15x15>();
            this.OR_ORDER_WORKERS = new HashSet<OR_ORDER_WORKERS>();
        }
    
        public decimal OR_ID { get; set; }
        public Nullable<decimal> CL_ID { get; set; }
        public string WT_NAME { get; set; }
        public Nullable<System.DateTime> OR_DATE { get; set; }
        public Nullable<System.DateTime> OR_START_TIME { get; set; }
        public Nullable<System.DateTime> OR_END_TIME { get; set; }
        public string OR_ADDRESS { get; set; }
        public Nullable<decimal> OR_WORKERS_COUNT { get; set; }
        public Nullable<decimal> OR_COST_HUMAN_HOUR { get; set; }
        public Nullable<bool> OR_IS_CLOSED { get; set; }
        public string OR_HOW_TO_GET { get; set; }
        public string OR_COMMENT { get; set; }
        public string OR_DEPARTMENT { get; set; }
        public Nullable<System.DateTime> OR_DATECREATE { get; set; }
        public Nullable<decimal> OR_WH_LIST_NUM { get; set; }
        public Nullable<decimal> OR_COST_UNIT { get; set; }
        public decimal OR_POSITION_LAT { get; set; }
        public decimal OR_POSITION_LNG { get; set; }
        public bool OR_IS_COVEREMAIL_SENT { get; set; }
        public decimal OR_US_ID_CREATE { get; set; }
        public decimal OR_US_ID_CLOSE { get; set; }
        public System.DateTime OR_CREATE_DATETIME { get; set; }
        public System.DateTime OR_CLOSE_DATETIME { get; set; }
        public bool OR_IS_COVEREMAIL_ERROR { get; set; }
        public decimal US_ID_COVEREMAIL { get; set; }
        public bool OR_IS_MISTAKEN { get; set; }
        public decimal OR_GENDER { get; set; }
        public decimal OR_PRIORITY { get; set; }
        public bool OR_IS_TECHNICAL { get; set; }
        public Nullable<decimal> CND_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_CALL_RESULTS> CC_CALL_RESULTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_IPTEL_LOGS> CC_IPTEL_LOGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_IPTEL_TASK_ORDER> CC_IPTEL_TASK_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_WORKER_REMINDS> CC_WORKER_REMINDS { get; set; }
        public virtual CL_CLIENTS CL_CLIENTS { get; set; }
        public virtual CL_PRIORITY CL_PRIORITY { get; set; }
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
        public virtual OR_LUOV OR_LUOV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_COSTS> OR_ORDER_COSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_HISTORY> OR_ORDER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_RANGE_REQUIREMENTS> OR_RANGE_REQUIREMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_RECRUITER_HISTORY> WR_RECRUITER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_COMMENTS> OR_ORDER_COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_PRE_ADD> OR_PRE_ADD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_QUEUE_ACTUALISATION> OR_QUEUE_ACTUALISATION { get; set; }
        public virtual OR_TRAIN_CENTER_AVAILABLE OR_TRAIN_CENTER_AVAILABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_ACTION_15x15> WR_ACTION_15x15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_WORKERS> OR_ORDER_WORKERS { get; set; }
    }
}
