//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ORDER_HISTORY
    {
        public int ORDER_HISTORY_ID { get; set; }
        public decimal OR_ID { get; set; }
        public int STATUS_ID { get; set; }
        public int CON_ID { get; set; }
        public System.DateTime EDIT_TIME { get; set; }
        public decimal US_ID { get; set; }
    
        public virtual CL_CONTRACT CL_CONTRACT { get; set; }
        public virtual OPT_STATUS OPT_STATUS { get; set; }
        public virtual OR_ORDER OR_ORDER { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
