//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ORDER_COMMENTS
    {
        public decimal OR_ID { get; set; }
        public decimal OC_ID { get; set; }
        public decimal US_ID { get; set; }
        public string OC_COMMENT { get; set; }
        public System.DateTime OC_DATE { get; set; }
    
        public virtual OR_ORDER OR_ORDER { get; set; }
    }
}
