//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_PRE_ADD
    {
        public decimal OR_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime OPA_CREATE { get; set; }
    
        public virtual OR_ORDER OR_ORDER { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
