//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_QUEUE_ACTUALISATION
    {
        public decimal ORQA_ID { get; set; }
        public decimal OR_ID { get; set; }
        public decimal ORQA_STAGE { get; set; }
        public System.DateTime ORQA_STARTED_TIME { get; set; }
        public System.DateTime ORQA_DONE_TIME { get; set; }
        public bool ORQA_DONE { get; set; }
        public bool ORQA_STAFFED { get; set; }
        public decimal ORQUAP_POOL_ID { get; set; }
    
        public virtual OR_ORDER OR_ORDER { get; set; }
    }
}
