//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_TRAIN_CENTER_WORKERS_CAMPAIGN
    {
        public decimal CGN_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
    
        public virtual CGN_CAMPAIGN_WORKERS CGN_CAMPAIGN_WORKERS { get; set; }
        public virtual OR_TRAIN_CENTER_AVAILABLE_CAMPAIGNS OR_TRAIN_CENTER_AVAILABLE_CAMPAIGNS { get; set; }
    }
}
