//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_TRAIN_CENTER_AVAILABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OR_TRAIN_CENTER_AVAILABLE()
        {
            this.OR_TRAIN_CENTER_WORKERS = new HashSet<OR_TRAIN_CENTER_WORKERS>();
        }
    
        public decimal OR_ID { get; set; }
        public decimal ORTC_WORKERS_MAX { get; set; }
    
        public virtual OR_ORDER OR_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_TRAIN_CENTER_WORKERS> OR_TRAIN_CENTER_WORKERS { get; set; }
    }
}
