//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REASONS_FIRE_MACHINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REASONS_FIRE_MACHINE()
        {
            this.FIRE_MACHINE_HISTORY = new HashSet<FIRE_MACHINE_HISTORY>();
        }
    
        public int REASON_ID { get; set; }
        public string REASON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIRE_MACHINE_HISTORY> FIRE_MACHINE_HISTORY { get; set; }
    }
}
