//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_AUTHORIZATION_LOG
    {
        public decimal USAL_ID { get; set; }
        public decimal USAL_USID { get; set; }
        public System.DateTime USAL_LOGIN_DTIME { get; set; }
        public System.DateTime USAL_LASTCHK_DTIME { get; set; }
        public System.DateTime USAL_DATE { get; set; }
    }
}
