//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_BANK_SIGNS_RESP
    {
        public int BSR_ID { get; set; }
        public decimal US_ID { get; set; }
        public decimal SCUP_ID { get; set; }
        public decimal AB_ID { get; set; }
    
        public virtual AC_BANKS AC_BANKS { get; set; }
        public virtual SC_UNIT_PLACES SC_UNIT_PLACES { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
