//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_USER_ROLES
    {
        public string ROL_ROLENAME { get; set; }
        public decimal US_ID { get; set; }
    
        public virtual SC_ROLES SC_ROLES { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
