//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SC_USERS()
        {
            this.AC_ACCURAL = new HashSet<AC_ACCURAL>();
            this.AC_BANKS_UNITS = new HashSet<AC_BANKS_UNITS>();
            this.AC_INTEGRATION_TRANSFERS = new HashSet<AC_INTEGRATION_TRANSFERS>();
            this.AC_INTEGRATION_TRANSFERS1 = new HashSet<AC_INTEGRATION_TRANSFERS>();
            this.BANK_TRANSFERS_HISTORY = new HashSet<BANK_TRANSFERS_HISTORY>();
            this.CC_CALL_RESULTS = new HashSet<CC_CALL_RESULTS>();
            this.CC_IPTEL_LOGS = new HashSet<CC_IPTEL_LOGS>();
            this.CC_MANAGER_TASK = new HashSet<CC_MANAGER_TASK>();
            this.CC_WORKER_REMINDS = new HashSet<CC_WORKER_REMINDS>();
            this.CL_ACTUAL_SETTINGS_TRANSACTIONS = new HashSet<CL_ACTUAL_SETTINGS_TRANSACTIONS>();
            this.CL_BLACKLIST = new HashSet<CL_BLACKLIST>();
            this.CL_CLIENTS_USERS = new HashSet<CL_CLIENTS_USERS>();
            this.CL_CLOSED_PERIODS = new HashSet<CL_CLOSED_PERIODS>();
            this.CL_CONTRACT = new HashSet<CL_CONTRACT>();
            this.CL_CONTRACT1 = new HashSet<CL_CONTRACT>();
            this.FUN_MAGIC_BUTTON = new HashSet<FUN_MAGIC_BUTTON>();
            this.INV_HISTORY = new HashSet<INV_HISTORY>();
            this.INV_INVOICE = new HashSet<INV_INVOICE>();
            this.INV_SENT_EMAILS = new HashSet<INV_SENT_EMAILS>();
            this.INV_SENT_EMAILS1 = new HashSet<INV_SENT_EMAILS>();
            this.LE_OBLIGATION_HISTORY = new HashSet<LE_OBLIGATION_HISTORY>();
            this.LOG_CC_IN_OUT = new HashSet<LOG_CC_IN_OUT>();
            this.NT_BLACKLIST = new HashSet<NT_BLACKLIST>();
            this.OR_LUOV = new HashSet<OR_LUOV>();
            this.OR_ORDER_COSTS_HISTORY = new HashSet<OR_ORDER_COSTS_HISTORY>();
            this.OR_ORDER_HISTORY = new HashSet<OR_ORDER_HISTORY>();
            this.OR_ORDER_WORKER_HISTORY = new HashSet<OR_ORDER_WORKER_HISTORY>();
            this.SC_BANK_SIGNS_RESP = new HashSet<SC_BANK_SIGNS_RESP>();
            this.WR_CHARGE_HISTORY = new HashSet<WR_CHARGE_HISTORY>();
            this.WR_INTERNAL_CONTRACT = new HashSet<WR_INTERNAL_CONTRACT>();
            this.WR_INTERNAL_CONTRACT1 = new HashSet<WR_INTERNAL_CONTRACT>();
            this.WR_INTERNAL_CONTRACT2 = new HashSet<WR_INTERNAL_CONTRACT>();
            this.WR_KEEPING = new HashSet<WR_KEEPING>();
            this.WR_KEEPING_HISTORY = new HashSet<WR_KEEPING_HISTORY>();
            this.WR_PENALTY_HISTORY = new HashSet<WR_PENALTY_HISTORY>();
            this.WR_RECRUITER_PERIOD_HISTORY = new HashSet<WR_RECRUITER_PERIOD_HISTORY>();
            this.WR_BANK_PROFILES = new HashSet<WR_BANK_PROFILES>();
            this.WR_CARDS_LOST = new HashSet<WR_CARDS_LOST>();
            this.WR_LABOR_CONTRACTS = new HashSet<WR_LABOR_CONTRACTS>();
            this.WR_PAYMENT_HISTORY = new HashSet<WR_PAYMENT_HISTORY>();
            this.WR_WORKER_VACATIONS = new HashSet<WR_WORKER_VACATIONS>();
            this.TMP_RETURN_KEEPING = new HashSet<TMP_RETURN_KEEPING>();
            this.CC_IPTEL_TASKS = new HashSet<CC_IPTEL_TASKS>();
            this.SC_UNIT = new HashSet<SC_UNIT>();
        }
    
        public decimal US_ID { get; set; }
        public string US_USERNAME { get; set; }
        public string US_PASSWORD { get; set; }
        public string ROL_ROLENAME { get; set; }
        public string US_FAMILY_NAME { get; set; }
        public string US_FATHER_NAME { get; set; }
        public string US_NAME { get; set; }
        public string US_COMMENT { get; set; }
        public Nullable<decimal> WR_ID { get; set; }
        public Nullable<decimal> UN_ID { get; set; }
        public Nullable<System.DateTime> US_PASSSET { get; set; }
        public bool US_ALLOWINTERNET { get; set; }
        public string US_EMAIL { get; set; }
        public bool IS_PASSWORD_RESET { get; set; }
        public string SCU_LDAP_ACCOUNT { get; set; }
        public bool SCU_IS_SYSTEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_ACCURAL> AC_ACCURAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_BANKS_UNITS> AC_BANKS_UNITS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_INTEGRATION_TRANSFERS> AC_INTEGRATION_TRANSFERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_INTEGRATION_TRANSFERS> AC_INTEGRATION_TRANSFERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANK_TRANSFERS_HISTORY> BANK_TRANSFERS_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_CALL_RESULTS> CC_CALL_RESULTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_IPTEL_LOGS> CC_IPTEL_LOGS { get; set; }
        public virtual CC_IPTEL_USERS_STATUSES CC_IPTEL_USERS_STATUSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_MANAGER_TASK> CC_MANAGER_TASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_WORKER_REMINDS> CC_WORKER_REMINDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_ACTUAL_SETTINGS_TRANSACTIONS> CL_ACTUAL_SETTINGS_TRANSACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_BLACKLIST> CL_BLACKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLIENTS_USERS> CL_CLIENTS_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CLOSED_PERIODS> CL_CLOSED_PERIODS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT> CL_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_CONTRACT> CL_CONTRACT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUN_MAGIC_BUTTON> FUN_MAGIC_BUTTON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_HISTORY> INV_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_INVOICE> INV_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SENT_EMAILS> INV_SENT_EMAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SENT_EMAILS> INV_SENT_EMAILS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LE_OBLIGATION_HISTORY> LE_OBLIGATION_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_CC_IN_OUT> LOG_CC_IN_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NT_BLACKLIST> NT_BLACKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_LUOV> OR_LUOV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_COSTS_HISTORY> OR_ORDER_COSTS_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_HISTORY> OR_ORDER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_WORKER_HISTORY> OR_ORDER_WORKER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SC_BANK_SIGNS_RESP> SC_BANK_SIGNS_RESP { get; set; }
        public virtual SC_ROLES SC_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_CHARGE_HISTORY> WR_CHARGE_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERNAL_CONTRACT> WR_INTERNAL_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERNAL_CONTRACT> WR_INTERNAL_CONTRACT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERNAL_CONTRACT> WR_INTERNAL_CONTRACT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_KEEPING> WR_KEEPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_KEEPING_HISTORY> WR_KEEPING_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_PENALTY_HISTORY> WR_PENALTY_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_RECRUITER_PERIOD_HISTORY> WR_RECRUITER_PERIOD_HISTORY { get; set; }
        public virtual WR_SUPERVISORS WR_SUPERVISORS { get; set; }
        public virtual SC_USER_ROLES SC_USER_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_BANK_PROFILES> WR_BANK_PROFILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_CARDS_LOST> WR_CARDS_LOST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_LABOR_CONTRACTS> WR_LABOR_CONTRACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_PAYMENT_HISTORY> WR_PAYMENT_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_VACATIONS> WR_WORKER_VACATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMP_RETURN_KEEPING> TMP_RETURN_KEEPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_IPTEL_TASKS> CC_IPTEL_TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SC_UNIT> SC_UNIT { get; set; }
    }
}
