//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_UNIT_PLACES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SC_UNIT_PLACES()
        {
            this.SC_BANK_SIGNS_RESP = new HashSet<SC_BANK_SIGNS_RESP>();
            this.SC_PLACES_SMS = new HashSet<SC_PLACES_SMS>();
            this.WR_INTERVIEW = new HashSet<WR_INTERVIEW>();
        }
    
        public decimal UN_ID { get; set; }
        public decimal SCUP_ID { get; set; }
        public string SCUP_NAME { get; set; }
        public bool SCUP_IS_INTERVIEW_PLACE { get; set; }
        public string SCUP_ADDRESS { get; set; }
        public string SCUP_HOWTOGET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SC_BANK_SIGNS_RESP> SC_BANK_SIGNS_RESP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SC_PLACES_SMS> SC_PLACES_SMS { get; set; }
        public virtual SC_UNIT SC_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERVIEW> WR_INTERVIEW { get; set; }
    }
}
