//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_RECEIVED_MSG
    {
        public decimal SR_ID { get; set; }
        public decimal SRM_ID { get; set; }
        public long SRM_RESP_ID { get; set; }
        public string SRM_SRC_NUMBER { get; set; }
        public string SRM_NUMBER { get; set; }
        public string SRM_TEXT { get; set; }
        public System.DateTime SRM_DATETIME { get; set; }
        public bool SRM_PROCESSED { get; set; }
    
        public virtual SMS_RECEIVE_REQUESTS SMS_RECEIVE_REQUESTS { get; set; }
    }
}
