//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_TEMPLATES_PARAMS
    {
        public int ID_SETTING { get; set; }
        public int ID_FIELD { get; set; }
        public int ID_CONDITION { get; set; }
        public int ID_SMS_TEMPLATE { get; set; }
        public string VALUE { get; set; }
    
        public virtual SMS_TEMPLATES SMS_TEMPLATES { get; set; }
        public virtual SYS_CONDITIONS SYS_CONDITIONS { get; set; }
        public virtual SYS_FIELDS SYS_FIELDS { get; set; }
    }
}
