//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_TEMPLATES_HISTORY
    {
        public int ID { get; set; }
        public int ID_SMS_TEMPLATE { get; set; }
        public System.DateTime EDIT_DATE { get; set; }
        public decimal US_ID { get; set; }
        public string COMMENT { get; set; }
    
        public virtual SMS_TEMPLATES SMS_TEMPLATES { get; set; }
    }
}
