//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_SEND_CONDITIONS_TYPES
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string KEY_CHAR_VALUE { get; set; }
    
        public virtual SMS_SEND_CONDITIONS SMS_SEND_CONDITIONS { get; set; }
    }
}
