//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_SEND_CONDITIONS
    {
        public int ID_TYPE { get; set; }
        public Nullable<int> ID_SMS_TEMPLATE { get; set; }
        public string VALUE { get; set; }
    
        public virtual SMS_SEND_CONDITIONS_TYPES SMS_SEND_CONDITIONS_TYPES { get; set; }
        public virtual SMS_TEMPLATES SMS_TEMPLATES { get; set; }
    }
}
