//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_TEMPLATES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMS_TEMPLATES()
        {
            this.SMS_SEND_CONDITIONS = new HashSet<SMS_SEND_CONDITIONS>();
            this.SMS_TEMPLATES_HISTORY = new HashSet<SMS_TEMPLATES_HISTORY>();
            this.SMS_TEMPLATES_PARAMS = new HashSet<SMS_TEMPLATES_PARAMS>();
        }
    
        public int ID { get; set; }
        public int ID_SMS_EVENT { get; set; }
        public bool IS_SEND { get; set; }
        public string NAME { get; set; }
        public string MESSAGE { get; set; }
        public bool IS_NEED_TRANSLIT { get; set; }
        public bool IS_DEFAULT { get; set; }
    
        public virtual OPT_SMS_EVENTS OPT_SMS_EVENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS_SEND_CONDITIONS> SMS_SEND_CONDITIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS_TEMPLATES_HISTORY> SMS_TEMPLATES_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS_TEMPLATES_PARAMS> SMS_TEMPLATES_PARAMS { get; set; }
    }
}
