//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONDITIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_CONDITIONS()
        {
            this.SMS_TEMPLATES_PARAMS = new HashSet<SMS_TEMPLATES_PARAMS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string KEY_CHAR_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMS_TEMPLATES_PARAMS> SMS_TEMPLATES_PARAMS { get; set; }
        public virtual SYS_FIELDS_TYPES SYS_FIELDS_TYPES { get; set; }
    }
}
