//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_WR_DISMISSAL_ITEMS
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal OPTD_ID { get; set; }
        public bool IS_CHECKED { get; set; }
        public int DISM_ITEM_COUNTER { get; set; }
        public decimal WHO_WRITE_OFF { get; set; }
        public decimal WHO_GIVE { get; set; }
        public System.DateTime WHEN_GIVE { get; set; }
        public System.DateTime WHEN_WRITE_OFF { get; set; }
    }
}
