//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORARY_AC_ACCURAL
    {
        public decimal US_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal ACC_ID { get; set; }
        public string ACC_COMMENT { get; set; }
        public decimal ACC_SUM { get; set; }
        public Nullable<decimal> ACC_OR_ID { get; set; }
        public Nullable<bool> ACC_IS_INCOME { get; set; }
        public Nullable<bool> ACC_IS_CALC { get; set; }
        public Nullable<System.DateTime> ACC_DATE { get; set; }
        public System.DateTime ACC_DATETIME { get; set; }
        public byte ACC_CALC_TYPE { get; set; }
        public bool ACC_IS_CALC_GIVED { get; set; }
        public System.DateTime ACC_GIVED_DATE { get; set; }
        public bool ACC_IS_CALC_TRANSFERRED { get; set; }
        public int AAT_ID { get; set; }
    }
}
