//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_old_order_costs
    {
        public decimal or_id { get; set; }
        public Nullable<decimal> OR_COST_HUMAN_HOUR { get; set; }
    }
}
