//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_RETURN_KEEPING
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal KP_ID { get; set; }
        public Nullable<System.DateTime> RK_DATE_INSERT { get; set; }
        public decimal RK_ID { get; set; }
        public Nullable<decimal> US_ID { get; set; }
        public Nullable<decimal> RK_PER_SUM { get; set; }
        public Nullable<decimal> RK_LAST_COUNT { get; set; }
        public Nullable<bool> RK_IS_TO_RETURN { get; set; }
    
        public virtual OPT_KEEPING OPT_KEEPING { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
