//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_calc_worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmp_calc_worker()
        {
            this.AC_ACCURAL = new HashSet<AC_ACCURAL>();
        }
    
        public int Id { get; set; }
        public decimal UnId { get; set; }
        public decimal WrId { get; set; }
        public int FileId { get; set; }
        public int CalcType { get; set; }
        public bool ShouldFire { get; set; }
        public string State { get; set; }
    
        public virtual tmp_calc_file tmp_calc_file { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_ACCURAL> AC_ACCURAL { get; set; }
    }
}
