//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_ACTION_BONUSES20x100
    {
        public decimal AB_ID { get; set; }
        public decimal ACC_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public System.DateTime WHEN_BONUS_GIVED { get; set; }
        public decimal WR_BONUS_SUM { get; set; }
        public Nullable<decimal> ACC_ID_NEXT { get; set; }
    }
}
