//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_CH_CARD_ITEM
    {
        public int CH_CARD_IT_ID { get; set; }
        public Nullable<int> CH_CARD_ID { get; set; }
        public Nullable<int> CH_IT_ID { get; set; }
    
        public virtual OPT_CH_ITEM OPT_CH_ITEM { get; set; }
        public virtual WR_CH_CARD WR_CH_CARD { get; set; }
    }
}
