//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_CHARGE_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_CHARGE_HISTORY()
        {
            this.AC_ACCRUAL_WR_CHARGE = new HashSet<AC_ACCRUAL_WR_CHARGE>();
        }
    
        public int WCH_ID { get; set; }
        public int WRC_ID { get; set; }
        public byte OPS_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime WCH_DATETIME { get; set; }
        public string WCH_COMMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_ACCRUAL_WR_CHARGE> AC_ACCRUAL_WR_CHARGE { get; set; }
        public virtual OPT_PENALTY_STATUS OPT_PENALTY_STATUS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_CHARGE WR_CHARGE { get; set; }
    }
}
