//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_CARDS_LOST
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal WCL_ID { get; set; }
        public string WR_CARDNUM { get; set; }
        public string WR_CARD_ACCOUNT_NUMBER { get; set; }
        public decimal WRCL_USER { get; set; }
        public System.DateTime WRCL_DATETIME { get; set; }
        public string WCL_ID_CARD { get; set; }
        public Nullable<System.DateTime> CARD_APPLIED_DATE { get; set; }
        public Nullable<System.DateTime> CARD_ISSUED_DATE { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
