//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_DataType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_DataType()
        {
            this.CL_JURI_NAMES_EXTENSIONS_TYPE = new HashSet<CL_JURI_NAMES_EXTENSIONS_TYPE>();
            this.WR_WORKERS_EXTENSIONS_TYPE = new HashSet<WR_WORKERS_EXTENSIONS_TYPE>();
        }
    
        public decimal TypeID { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_JURI_NAMES_EXTENSIONS_TYPE> CL_JURI_NAMES_EXTENSIONS_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKERS_EXTENSIONS_TYPE> WR_WORKERS_EXTENSIONS_TYPE { get; set; }
    }
}
