//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_DISMISSAL_ITEMS_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_DISMISSAL_ITEMS_HISTORY()
        {
            this.WR_DISMISSAL_HIST_ACCRUAL = new HashSet<WR_DISMISSAL_HIST_ACCRUAL>();
        }
    
        public int HI_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public int STATUS_ID { get; set; }
        public int WRDI_ID { get; set; }
    
        public virtual OPT_STATUS OPT_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_DISMISSAL_HIST_ACCRUAL> WR_DISMISSAL_HIST_ACCRUAL { get; set; }
        public virtual WR_DISMISSAL_ITEMS WR_DISMISSAL_ITEMS { get; set; }
    }
}
