//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_DISMISSAL_HIST_ACCRUAL
    {
        public decimal ACC_ID { get; set; }
        public int HI_ID { get; set; }
        public int ID { get; set; }
    
        public virtual AC_ACCURAL AC_ACCURAL { get; set; }
        public virtual WR_DISMISSAL_ITEMS_HISTORY WR_DISMISSAL_ITEMS_HISTORY { get; set; }
    }
}
