//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_DISMISSAL_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_DISMISSAL_ITEMS()
        {
            this.WR_DISMISSAL_ITEMS_HISTORY = new HashSet<WR_DISMISSAL_ITEMS_HISTORY>();
        }
    
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public int OPTD_ID { get; set; }
        public int WRDI_ID { get; set; }
    
        public virtual OPT_DISMISSAL_ITEMS OPT_DISMISSAL_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_DISMISSAL_ITEMS_HISTORY> WR_DISMISSAL_ITEMS_HISTORY { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
