//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_EDUCATION
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal WE_NUM { get; set; }
        public string WE_NAME { get; set; }
        public string WE_TYPE { get; set; }
        public string WE_PROFESSION { get; set; }
        public System.DateTime WE_DATE_START { get; set; }
        public System.DateTime WE_DATE_END { get; set; }
    }
}
