//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_GROUPS()
        {
            this.ACT_ACTIONS = new HashSet<ACT_ACTIONS>();
            this.OPT_SHIFTS_BEFORE_PAY = new HashSet<OPT_SHIFTS_BEFORE_PAY>();
            this.WR_MIN_RESTS = new HashSet<WR_MIN_RESTS>();
            this.WR_WAGES = new HashSet<WR_WAGES>();
            this.WR_WORKERS = new HashSet<WR_WORKERS>();
        }
    
        public decimal WRG_ID { get; set; }
        public string WRG_NAME { get; set; }
        public Nullable<bool> WRG_IS_DEFAULT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACT_ACTIONS> ACT_ACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_SHIFTS_BEFORE_PAY> OPT_SHIFTS_BEFORE_PAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_MIN_RESTS> WR_MIN_RESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WAGES> WR_WAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKERS> WR_WORKERS { get; set; }
    }
}
