//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_HISTORY
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal WRH_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime WRH_DATETIME { get; set; }
        public string WRH_COMMENT { get; set; }
        public decimal WRH_TYPE { get; set; }
        public Nullable<decimal> WRH_NEW_STATUS { get; set; }
    
        public virtual OPT_STATUSES OPT_STATUSES { get; set; }
    }
}
