//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_INTERVIEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_INTERVIEW()
        {
            this.WR_INTERVIEW_AND_WORKER = new HashSet<WR_INTERVIEW_AND_WORKER>();
        }
    
        public int Id { get; set; }
        public int IdInterViewType { get; set; }
        public string Name { get; set; }
        public decimal IdPlace { get; set; }
        public int IdSheduleItem { get; set; }
        public int Duration { get; set; }
        public string Address { get; set; }
        public string HowToGet { get; set; }
        public decimal US_ID { get; set; }
    
        public virtual OPT_INTERVIEW_TYPE OPT_INTERVIEW_TYPE { get; set; }
        public virtual SC_UNIT_PLACES SC_UNIT_PLACES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERVIEW_AND_WORKER> WR_INTERVIEW_AND_WORKER { get; set; }
        public virtual WR_SHEDULE_ITEM WR_SHEDULE_ITEM { get; set; }
    }
}
