//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_IMAGES
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal IN_ID { get; set; }
        public decimal WRI_NUM { get; set; }
        public string WRI_PATH { get; set; }
        public string WRI_COMMENT { get; set; }
    
        public virtual OPT_IMG_NAMES OPT_IMG_NAMES { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
