//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_INTERNAL_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_INTERNAL_CONTRACT()
        {
            this.WR_WAGES = new HashSet<WR_WAGES>();
        }
    
        public int WIC_ID { get; set; }
        public System.DateTime WIC_DATE_FROM { get; set; }
        public System.DateTime WIC_DATE_TO { get; set; }
        public decimal US_ADDED { get; set; }
        public System.DateTime DATE_ADDED { get; set; }
        public byte[] WIC_DATA { get; set; }
        public int FILE_EXT { get; set; }
        public string NUMBER { get; set; }
    
        public virtual OPT_FILE_EXTENSIONS OPT_FILE_EXTENSIONS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual SC_USERS SC_USERS1 { get; set; }
        public virtual SC_USERS SC_USERS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WAGES> WR_WAGES { get; set; }
    }
}
