//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_INVOICE_NUMBERS
    {
        public decimal WRIN_ID { get; set; }
        public int DOC_NUM { get; set; }
        public decimal UN_ID { get; set; }
        public string CREATOR { get; set; }
        public decimal CLJN_ID { get; set; }
        public decimal OURJN_ID { get; set; }
        public decimal NT_ID { get; set; }
        public int DOC_STATE { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public System.DateTime UNLOADING_DATE { get; set; }
        public decimal CL_ID { get; set; }
    }
}
