//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_INTERVIEW_AND_WORKER
    {
        public int Id { get; set; }
        public int IdInterview { get; set; }
        public decimal IdTempProfile { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual WR_INTERVIEW WR_INTERVIEW { get; set; }
        public virtual WR_TEMP_PROFILES WR_TEMP_PROFILES { get; set; }
    }
}
