//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_KEEPING_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_KEEPING_HISTORY()
        {
            this.AC_ACCRUAL_KEEPING = new HashSet<AC_ACCRUAL_KEEPING>();
        }
    
        public int WKH_ID { get; set; }
        public int WRK_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime WKH_DATE { get; set; }
        public int WKH_ORDER_COUNT { get; set; }
        public byte OKS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_ACCRUAL_KEEPING> AC_ACCRUAL_KEEPING { get; set; }
        public virtual OPT_KEEPING_STATUS OPT_KEEPING_STATUS { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_KEEPING WR_KEEPING { get; set; }
    }
}
