//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_KLADR_COUNTRIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_KLADR_COUNTRIES()
        {
            this.OPT_DOCS_STATES = new HashSet<OPT_DOCS_STATES>();
            this.OPT_HOSTEL = new HashSet<OPT_HOSTEL>();
        }
    
        public decimal WKC_ID { get; set; }
        public string WKC_NAME { get; set; }
        public string KeyCharValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_DOCS_STATES> OPT_DOCS_STATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_HOSTEL> OPT_HOSTEL { get; set; }
    }
}
