//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_KLADR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_KLADR()
        {
            this.OPT_HOSTEL = new HashSet<OPT_HOSTEL>();
            this.OPT_HOSTEL1 = new HashSet<OPT_HOSTEL>();
            this.OPT_HOSTEL2 = new HashSet<OPT_HOSTEL>();
            this.OPT_HOSTEL3 = new HashSet<OPT_HOSTEL>();
        }
    
        public decimal WK_ID { get; set; }
        public string WK_NAME { get; set; }
        public string WK_TYPE { get; set; }
        public string WK_CODE { get; set; }
        public string WK_POST_INDEX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_HOSTEL> OPT_HOSTEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_HOSTEL> OPT_HOSTEL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_HOSTEL> OPT_HOSTEL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPT_HOSTEL> OPT_HOSTEL3 { get; set; }
    }
}
