//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_KLADR_LESS
    {
        public string WKL_LESS_NAME { get; set; }
        public string WKL_NAME { get; set; }
    
        public virtual WR_ROSEURO_IDS WR_ROSEURO_IDS { get; set; }
    }
}
