//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_LOG_KEEPING
    {
        public Nullable<decimal> UN_ID { get; set; }
        public Nullable<decimal> WR_ID { get; set; }
        public string KP_NAME { get; set; }
        public Nullable<System.DateTime> KP_DATE_INSERT { get; set; }
        public Nullable<decimal> KP_SUM { get; set; }
        public Nullable<decimal> US_ID { get; set; }
        public decimal WRLK_ID { get; set; }
        public Nullable<decimal> US_KEEPER_ID { get; set; }
        public Nullable<System.DateTime> KP_DATE_KEEP { get; set; }
        public Nullable<bool> KP_BEEN_KEEPED { get; set; }
        public Nullable<decimal> KP_ORDER_COUNT_DIVIDE { get; set; }
    }
}
