//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_LABOR_CONTRACTS
    {
        public int WRLC_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public string WRLC_NUMBER { get; set; }
        public System.DateTime WRLC_DATE { get; set; }
        public System.DateTime WRLC_PERIOD_START { get; set; }
        public System.DateTime WRLC_PERIOD_END { get; set; }
        public System.DateTime WRLC_ISSUING_DATE { get; set; }
        public decimal US_ID { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
