//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_MIN_RESTS
    {
        public decimal UN_ID { get; set; }
        public decimal WRG_ID { get; set; }
        public decimal MIN_REST { get; set; }
    
        public virtual SC_UNIT SC_UNIT { get; set; }
        public virtual WR_GROUPS WR_GROUPS { get; set; }
    }
}
