//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_MEDICAL_BOOKS
    {
        public decimal WRMB_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public System.DateTime WRMB_DATE_GIVED { get; set; }
        public System.DateTime WRMB_DATE_UPDATE { get; set; }
        public System.DateTime WRMB_DATE_EXPIRED { get; set; }
        public string WRMB_NUM { get; set; }
    
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
