//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_PREVIOUS_WORK
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal WPW_NUM { get; set; }
        public string WPW_COMPANY_NAME { get; set; }
        public string WPW_COMPANY_ADDRESS { get; set; }
        public string WPW_COMPANY_PHONE { get; set; }
        public System.DateTime WPW_DATE_START { get; set; }
        public System.DateTime WPW_DATE_END { get; set; }
        public string WPW_POSITION { get; set; }
        public decimal WPW_SALARY { get; set; }
        public string WPW_WHY_LEFT { get; set; }
    }
}
