//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_PENALTIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_PENALTIES()
        {
            this.WR_PENALTY_HISTORY = new HashSet<WR_PENALTY_HISTORY>();
        }
    
        public decimal PEN_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal OR_ID { get; set; }
        public decimal WR_PENALTY_TYPE { get; set; }
        public byte WRP_IS_CONFIRMED { get; set; }
        public decimal WRP_PRICE { get; set; }
    
        public virtual OPT_PENALTY_STATUS OPT_PENALTY_STATUS { get; set; }
        public virtual OPT_PENALTY_TYPES OPT_PENALTY_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_PENALTY_HISTORY> WR_PENALTY_HISTORY { get; set; }
    }
}
