//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_PAYMENT_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_PAYMENT_HISTORY()
        {
            this.BANK_TRANSFERS_PAYMENT_HISTORY = new HashSet<BANK_TRANSFERS_PAYMENT_HISTORY>();
            this.WR_PAYMENT_HISTORY_ACCRUAL = new HashSet<WR_PAYMENT_HISTORY_ACCRUAL>();
        }
    
        public int CALC_ID { get; set; }
        public int PH_ID { get; set; }
        public bool ACCEPTED { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public decimal US_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANK_TRANSFERS_PAYMENT_HISTORY> BANK_TRANSFERS_PAYMENT_HISTORY { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_PAYMENT WR_PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_PAYMENT_HISTORY_ACCRUAL> WR_PAYMENT_HISTORY_ACCRUAL { get; set; }
    }
}
