//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_RECOMMENDATION
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal WRR_NUM { get; set; }
        public string WRR_NAME { get; set; }
        public string WRR_POSITION { get; set; }
        public string WRR_COMPANY { get; set; }
        public string WRR_PHONE { get; set; }
    }
}
