//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_RECRUITER_PERIOD_HISTORY
    {
        public int WRRPH_ID { get; set; }
        public int WRRP_ID { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime WRRPH_DATETIME { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_RECRUITER_PERIOD WR_RECRUITER_PERIOD { get; set; }
    }
}
