//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_RECRUITER_PERIOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_RECRUITER_PERIOD()
        {
            this.WR_RECRUITER_HISTORY = new HashSet<WR_RECRUITER_HISTORY>();
            this.WR_RECRUITER_PERIOD_HISTORY = new HashSet<WR_RECRUITER_PERIOD_HISTORY>();
        }
    
        public int WRRP_ID { get; set; }
        public int WRR_ID { get; set; }
        public byte ORT_ID { get; set; }
        public decimal WRR_SUM { get; set; }
        public System.DateTime WRRP_START { get; set; }
        public System.DateTime WRRP_END { get; set; }
    
        public virtual OPT_RECRUITER_TYPE OPT_RECRUITER_TYPE { get; set; }
        public virtual WR_RECRUITER WR_RECRUITER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_RECRUITER_HISTORY> WR_RECRUITER_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_RECRUITER_PERIOD_HISTORY> WR_RECRUITER_PERIOD_HISTORY { get; set; }
    }
}
