//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_RECRUITER_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_RECRUITER_HISTORY()
        {
            this.AC_ACCRUAL_RECRUITER = new HashSet<AC_ACCRUAL_RECRUITER>();
        }
    
        public int WRRH_ID { get; set; }
        public int WRRP_ID { get; set; }
        public decimal OR_ID { get; set; }
        public decimal WRRH_AMOUNT { get; set; }
        public System.DateTime WRRH_DATETIME { get; set; }
        public bool WRRH_IS_PLUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_ACCRUAL_RECRUITER> AC_ACCRUAL_RECRUITER { get; set; }
        public virtual OR_ORDER OR_ORDER { get; set; }
        public virtual WR_RECRUITER_PERIOD WR_RECRUITER_PERIOD { get; set; }
    }
}
