//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_RECRUITER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_RECRUITER()
        {
            this.WR_RECRUITER_PERIOD = new HashSet<WR_RECRUITER_PERIOD>();
        }
    
        public int WRR_ID { get; set; }
        public decimal UN_ID_MASTER { get; set; }
        public decimal WR_ID_MASTER { get; set; }
        public decimal UN_ID_SLAVE { get; set; }
        public decimal WR_ID_SLAVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_RECRUITER_PERIOD> WR_RECRUITER_PERIOD { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
        public virtual WR_WORKERS WR_WORKERS1 { get; set; }
    }
}
