//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_SUPERVISORS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_SUPERVISORS()
        {
            this.CL_SUPERVISORS = new HashSet<CL_SUPERVISORS>();
        }
    
        public decimal OST_ID { get; set; }
        public decimal SCU_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_SUPERVISORS> CL_SUPERVISORS { get; set; }
        public virtual OPT_SUPERVISOR_TYPES OPT_SUPERVISOR_TYPES { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
    }
}
