//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_SHEDULE_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_SHEDULE_ITEM()
        {
            this.WR_INTERVIEW = new HashSet<WR_INTERVIEW>();
        }
    
        public int Id { get; set; }
        public int IdShedule { get; set; }
        public System.DateTime StartTime { get; set; }
    
        public virtual OPT_SHEDULE OPT_SHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERVIEW> WR_INTERVIEW { get; set; }
    }
}
