//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_SMS
    {
        public decimal WRS_ID { get; set; }
        public string WRS_SMSTEXT { get; set; }
        public string WRS_SMSNUMBER { get; set; }
        public decimal WRS_SMSCOUNT { get; set; }
        public bool WRS_SMSSENT { get; set; }
        public long WRS_PUSH_ID { get; set; }
        public decimal WRS_ERROR_ID { get; set; }
        public decimal WRS_STATUS_ID { get; set; }
        public System.DateTime WRS_LASTCHK_DATE { get; set; }
        public int WRS_TYPE_ID { get; set; }
        public int UN_ID { get; set; }
        public int WR_ID { get; set; }
    
        public virtual WR_SMS_TYPES WR_SMS_TYPES { get; set; }
    }
}
