//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_TEMP_PROFILES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_TEMP_PROFILES()
        {
            this.WR_INTERVIEW_AND_WORKER = new HashSet<WR_INTERVIEW_AND_WORKER>();
        }
    
        public decimal WRT_ID { get; set; }
        public decimal WRT_UN_ID { get; set; }
        public string WRT_NAME { get; set; }
        public string WRT_FAMILY_NAME { get; set; }
        public string WRT_FATHER_NAME { get; set; }
        public string WRT_PHONE_NUM { get; set; }
        public System.DateTime WRT_INTERVIEW_DATE { get; set; }
        public decimal OIS_ID { get; set; }
        public bool WRT_IS_CONVERTED { get; set; }
        public decimal WRT_WR_UN_ID { get; set; }
        public decimal WRT_WR_WR_ID { get; set; }
        public decimal US_ID { get; set; }
        public bool WRT_RECALL { get; set; }
        public string WRT_VACANCY { get; set; }
        public decimal WRT_AGE { get; set; }
        public decimal WRT_IS_INCOMING_CALL { get; set; }
        public decimal SCUP_ID { get; set; }
        public string WRT_COMMENT { get; set; }
        public System.DateTime WRT_CREATED { get; set; }
        public bool WRT_IS_COME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_INTERVIEW_AND_WORKER> WR_INTERVIEW_AND_WORKER { get; set; }
    }
}
