//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_DOCUMENT_ATTR_CONTENT
    {
        public decimal ID { get; set; }
        public decimal ID_DOCUMENT_ATTR { get; set; }
        public string ATTR_CONTENT { get; set; }
        public System.DateTime CREATING_DATE { get; set; }
    
        public virtual WR_WORKER_DOCS_ATTRIBUTES WR_WORKER_DOCS_ATTRIBUTES { get; set; }
    }
}
