//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_ACTION_PAYMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_WORKER_ACTION_PAYMENTS()
        {
            this.WR_WORKER_ACTION_BRING_FRIEND = new HashSet<WR_WORKER_ACTION_BRING_FRIEND>();
            this.WR_WORKER_ACTION_PAYMENTS_HISTORY = new HashSet<WR_WORKER_ACTION_PAYMENTS_HISTORY>();
        }
    
        public int WWAP_ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public int AA_ID { get; set; }
        public System.DateTime WWAP_DATE { get; set; }
    
        public virtual ACT_ACTIONS ACT_ACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_ACTION_BRING_FRIEND> WR_WORKER_ACTION_BRING_FRIEND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_ACTION_PAYMENTS_HISTORY> WR_WORKER_ACTION_PAYMENTS_HISTORY { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
