//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WAGES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_WAGES()
        {
            this.CL_WR_WAGE = new HashSet<CL_WR_WAGE>();
            this.OR_ORDER_WORKER_HISTORY = new HashSet<OR_ORDER_WORKER_HISTORY>();
            this.WR_WAGES_OPTIONS = new HashSet<WR_WAGES_OPTIONS>();
            this.WR_WAGES1 = new HashSet<WR_WAGES>();
        }
    
        public string WT_NAME { get; set; }
        public decimal WRG_ID { get; set; }
        public decimal WRW_COST { get; set; }
        public decimal WRW_COST_INC { get; set; }
        public decimal WRW_HOURS_INC { get; set; }
        public int WRW_ID { get; set; }
        public Nullable<int> WRW_MASTER_ID { get; set; }
        public int WIC_ID { get; set; }
        public string WRW_NAME { get; set; }
        public bool IS_MISTAKEN { get; set; }
        public System.DateTime WRW_DATE_CREATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CL_WR_WAGE> CL_WR_WAGE { get; set; }
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OR_ORDER_WORKER_HISTORY> OR_ORDER_WORKER_HISTORY { get; set; }
        public virtual WR_GROUPS WR_GROUPS { get; set; }
        public virtual WR_INTERNAL_CONTRACT WR_INTERNAL_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WAGES_OPTIONS> WR_WAGES_OPTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WAGES> WR_WAGES1 { get; set; }
        public virtual WR_WAGES WR_WAGES2 { get; set; }
    }
}
