//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WAGES_OPTIONS_LMK
    {
        public int WRW_OPT_ID { get; set; }
        public decimal LMK_COST { get; set; }
    
        public virtual WR_WAGES_OPTIONS WR_WAGES_OPTIONS { get; set; }
    }
}
