//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WAGES_OPTIONS
    {
        public int WRW_OPT_ID { get; set; }
        public int WRW_ID { get; set; }
        public int OPT_TYPE_ID { get; set; }
    
        public virtual OPT_WAGE_OPTIONS_TYPE OPT_WAGE_OPTIONS_TYPE { get; set; }
        public virtual WR_WAGES WR_WAGES { get; set; }
        public virtual WR_WAGES_OPTIONS_LMK WR_WAGES_OPTIONS_LMK { get; set; }
    }
}
