//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_DOCUMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_WORKER_DOCUMENTS()
        {
            this.WR_WORKER_DOC_CONTENT = new HashSet<WR_WORKER_DOC_CONTENT>();
            this.WR_WORKER_DOCS_ATTRIBUTES = new HashSet<WR_WORKER_DOCS_ATTRIBUTES>();
        }
    
        public decimal ID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal DOC_STATE_ID { get; set; }
    
        public virtual OPT_DOCS_STATES OPT_DOCS_STATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_DOC_CONTENT> WR_WORKER_DOC_CONTENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKER_DOCS_ATTRIBUTES> WR_WORKER_DOCS_ATTRIBUTES { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
