//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_ACTION_PAYMENTS_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_WORKER_ACTION_PAYMENTS_HISTORY()
        {
            this.AC_ACCRUALS_WORKER_ACTION_PAYMENTS = new HashSet<AC_ACCRUALS_WORKER_ACTION_PAYMENTS>();
        }
    
        public int WWAPH_ID { get; set; }
        public int WWAP_ID { get; set; }
        public int US_ID { get; set; }
        public double WWAPH_SUM { get; set; }
        public System.DateTime WWAPH_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_ACCRUALS_WORKER_ACTION_PAYMENTS> AC_ACCRUALS_WORKER_ACTION_PAYMENTS { get; set; }
        public virtual WR_WORKER_ACTION_PAYMENTS WR_WORKER_ACTION_PAYMENTS { get; set; }
    }
}
