//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WAITING_FOR_FMS_RESPONSE
    {
        public decimal UnId { get; set; }
        public decimal WrId { get; set; }
        public decimal IdDocType { get; set; }
        public System.DateTime GeneratingDate { get; set; }
        public int Id { get; set; }
    
        public virtual OPT_DOCUMENT_TYPES OPT_DOCUMENT_TYPES { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
