//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKERS_EXTENSIONS
    {
        public decimal WrExtID { get; set; }
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public string DATA { get; set; }
        public decimal WR_WORKERS_EXTENSIONS_TYPE_ID { get; set; }
        public System.DateTime WR_DATE_CHANGE { get; set; }
        public decimal USER_ID { get; set; }
    
        public virtual WR_WORKERS_EXTENSIONS_TYPE WR_WORKERS_EXTENSIONS_TYPE { get; set; }
    }
}
