//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_VACATIONS
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public System.DateTime WRV_DATE { get; set; }
        public decimal US_ID { get; set; }
        public System.DateTime WRV_CREATE { get; set; }
        public int STATE_OF_MIND_ID { get; set; }
    
        public virtual OPT_DATE_STATE_MIND OPT_DATE_STATE_MIND { get; set; }
        public virtual SC_USERS SC_USERS { get; set; }
        public virtual WR_WORKERS WR_WORKERS { get; set; }
    }
}
