//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_WORK_TYPE
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public string WT_NAME { get; set; }
    
        public virtual OPT_WORK_TYPES OPT_WORK_TYPES { get; set; }
    }
}
