//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_COMMENTS
    {
        public decimal UN_ID { get; set; }
        public decimal WR_ID { get; set; }
        public decimal WC_ID { get; set; }
        public decimal US_ID { get; set; }
        public string WC_COMMENT { get; set; }
        public System.DateTime WC_DATE { get; set; }
    }
}
