//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKER_DOC_CONTENT
    {
        public decimal ID { get; set; }
        public decimal ID_WORKER_DOC { get; set; }
        public byte[] DATA_CONTENT { get; set; }
        public System.DateTime CREATING_DATE { get; set; }
    
        public virtual WR_WORKER_DOCUMENTS WR_WORKER_DOCUMENTS { get; set; }
    }
}
