//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WORKERS_EXTENSIONS_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_WORKERS_EXTENSIONS_TYPE()
        {
            this.WR_WORKERS_EXTENSIONS = new HashSet<WR_WORKERS_EXTENSIONS>();
        }
    
        public decimal ExtensionTypeID { get; set; }
        public string NAME { get; set; }
        public bool IsForeignKey { get; set; }
        public decimal WR_DataTypeId { get; set; }
        public string KEY_CHAR_VALUE { get; set; }
    
        public virtual WR_DataType WR_DataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WORKERS_EXTENSIONS> WR_WORKERS_EXTENSIONS { get; set; }
    }
}
